### ISSUE TITLE
Simple way of showing markdown output

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/markdown#115]
The `package:markdown` has already a `bin/markdown.dart` script which renders html, but it would be even nicer if it came with way to serve a valid html file, something like:
```
$ pub global activate markdown
$ pub global run markdown:serve myfile.md
See the rendered markdown at:  http://localhost:8080/myfile.html
```

**Comment by srawlins** [comment]
I think we should take the "one thing well" and "rule of composability" approach here. `bin/markdown.dart` can take files or stdin, and produce stdout. Your shell can redirect this output to a file, or another command, such as [bcat](https://rtomayko.github.io/bcat/).

Another reason is that adding an HTTP server adds dependencies. Currently this package has *zero* dependencies, making it super lightweight, and Dart doesn't have a notion of "binary dependencies" similar to "dev dependencies".

**Comment by mkustermann** [comment]
It is up to you to decide -- feel free to close the issue if you find this not to be a good fit for `package:markdown`.

But I think for convenience and usability it would be nice for users to have such a feature. A simple server using `dart:io`s `HttpServer` would also not increase dependencies.

**Comment by munificent** [comment]
> Another reason is that adding an HTTP server adds dependencies. Currently this package has zero dependencies, making it super lightweight, and Dart doesn't have a notion of "binary dependencies" similar to "dev dependencies".

One option is to put it in "example", not "bin". You'd have to clone the package yourself to run it, but it would be a nice place to put a handy reusable script among people who hack on the package. That would let you make any dependencies needed for it as dev_dependencies.

**Comment by srawlins** [comment]
@mkustermann Good call! If it can be done with HttpServer and nothing else, I love it. Accepting pull requests!

@munificent this is also a good "hack" (in my opinion, a hack; I do think there should be a bin_dependencies section). It'd be a fun project if anyone wanted to write a bcat port in dart. \*thinking... what am I doing this weekend...*

**Comment by mkustermann** [comment]
I think the functionality added in Issue #118 (namely adding a gh-pages app available at https://dart-lang.github.io/markdown/) solves this issue.
