### ISSUE TITLE
List items with code blocks not starting at beginning of line cause issues.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/markdown#116]
The following program (with the first 4 spaces removed) :

```dart
    import 'package:markdown/markdown.dart';
    
    String TEXT = r'''
    * before
    
      ```
    hello() => print('hello');
    ```
    
    between
    
       ```
    hello() => print('hello');
    ```
    
    after
    ''';
    
    main() {
      var blocks = new Document().parseLines(TEXT.split('\n'));
      print(new HtmlRenderer().render(blocks));
    }
```

Produces this output (with `package:markdown@0.11.0`):
```html
<ul><li>
<p>before</p>
<pre><code class="language-hello()"></code></pre></li></ul>
<pre><code>
between

</code></pre>
<p>hello() => print('hello');</p>
<pre><code>
after

</code></pre>
```

So there seems to be an issue with list items and code blocks starting at nonzero column.

The example was taken from the [dart-lang/angular2/master/CHANGELOG.md](https://raw.githubusercontent.com/dart-lang/angular2/master/CHANGELOG.md) file.

**Comment by srawlins** [comment]
Hi @mkustermann , what do you mean "the first four spaces removed? do you mean that your program is actually this?

    import 'package:markdown/markdown.dart';

    String TEXT = r'''
    * before

      ```
    hello() => print('hello');
    ```

    between

       ```
    hello() => print('hello');
    ```

    after
    ''';

    main() {
      var blocks = new Document().parseLines(TEXT.split('\n'));
      print(new HtmlRenderer().render(blocks));
    }

Why are the backticks misaligned? What is the desired output?

What if you wrote your markdown like this:

    import 'package:markdown/markdown.dart';

    String TEXT = r'''
    * before

      ```
      hello() => print('hello');
      ```

      between

      ```
      hello() => print('hello');
      ```

      after
    ''';

    main() {
      var blocks = new Document().parseLines(TEXT.split('\n'));
      print(new HtmlRenderer().render(blocks));
    }

**Comment by mkustermann** [comment]
> what do you mean "the first four spaces removed? do you mean that your program is actually this?

Yes - I just didn't know how to quote it because quoting using 3 backticks cannot be nested, so I indented it by 4 instead.

The backticks are misaligned because some users write markdown like that and the github implementation seems to support it (e.g. this [markdown](https://raw.githubusercontent.com/dart-lang/angular2/master/CHANGELOG.md) is rendered as this [html](https://github.com/dart-lang/angular2/blob/master/CHANGELOG.md) ) so I thought `package:markdown` should support it as well.

We use `package:markdown` to render readme/changelog files for pub.dartlang.org and would preferably get as close to how github renders markdown files as possible.

**Comment by srawlins** [comment]
I see. I think that the backticks, and their internal content, should be aligned. It looks nicer in the Markdown format, and is more consistent with other Markdown implementations ([Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+before%0A%0A++%60%60%60%0Ahello()+%3D%3E+print(%27hello%27)%3B%0A%60%60%60%0A%0A++between%0A%0A+++%60%60%60%0Ahello()+%3D%3E+print(%27hello%27)%3B%0A%60%60%60%0A%0A++after) shows a pretty inconsisdent rendering of that code, whereas the everything-in-a-list-item-should-be-indented-some text [renders... less fragmentedly](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+before%0A%0A++%60%60%60%0A++hello()+%3D%3E+print(%27hello%27)%3B%0A++%60%60%60%0A%0A++between%0A%0A++%60%60%60%0A++hello()+%3D%3E+print(%27hello%27)%3B%0A++%60%60%60%0A%0A++after) 😄 .

The markdown package is going for CommonMark compliance, which in some edge cases like this, disagrees with GitHub-Flavored Markdown (which I don't think is strongly specified anywhere...)

**Comment by kwalrath** [comment]
I authored that markdown. I'm not opposed to using the markdown you suggested, @srawlins, but I do remember that it was fairly tricky to get code within an indented section to work. I probably stopped at the first solution that seemed to work in github.

**Comment by kwalrath** [comment]
I should mention that there was no easy way to preview how the markdown would be interpreted, so I used gists. If you know of a better way preview markdown, I'd be happy to use and link to it.

**Comment by srawlins** [comment]
@kwalrath this is a frustrating missing feature today. I just filed #118 and #119 that would make this simpler. Otherwise I basically do what you do! I trust gist's output and it usually tracks with our package's output.

**Comment by kwalrath** [comment]
https://dart-lang.github.io/markdown/ is a great solution to my preview problem! Are you OK with me advertising it, @srawlins?

**Comment by srawlins** [comment]
Absolutely!

**Comment by srawlins** [comment]
Mind if I close this? The codeblock-in-a-list markup in the example is too loose for our parser. It happens to work for GitHub, but is not "standard" other than GitHub's parsing.

**Comment by kwalrath** [comment]
I'm fine with closing it, now that we have the preview tool.

**Comment by mkustermann** [comment]
I have also no objections, so let's just close it.
