### ISSUE TITLE
Launch a website showing rendered markdown

### ISSUE THREAD

**Issue by srawlins** [dart-lang/markdown#118]
This would be available at dart-lang.github.io/markdown.

**Comment by srawlins** [comment]
CC @kevmoo if you have any thoughts.

**Comment by kevmoo** [comment]
We could just add an `example` dir and do a little live editor. Shouldn't be too hard.

**Comment by srawlins** [comment]
The live editor is kind of what is proposed in #115 , right? I think this would be more useful when someone is writing their Dart package's README or CHANGELOG or doc comments, and they just quickly want to test some markdown. @kwalrath noted that she uses gists for this purpose. I don't want people to have to clone the repo.

**Comment by kevmoo** [comment]
> I don't want people to have to clone the repo.

Agreed! We make the app in `example` and then use https://github.com/kevmoo/peanut.dart/ to host it on dart-lang.github.io/markdown

**Comment by srawlins** [comment]
Oh i see! Fancy! I think I want to whip this up this afternoon.
