### ISSUE TITLE
4-space indent of sub-bullets renders incorrectly

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/markdown#14]
Consider this markdown for the shelf readme.

Render issues when put through markdown package: https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/shelf

Renders fine on github: https://github.com/dart-lang/bleeding_edge/blob/master/dart/pkg/shelf/README.md

Renders fine on pub.dartlang.org - http://pub.dartlang.org/packages/shelf

```markdown
* [Connect](http://www.senchalabs.org/connect/) for NodeJS.
    * Read [this great write-up](http://howtonode.org/connect-it) to understand
      the overall philosophy of all of these models.
* [Rack](http://rack.github.io/) for Ruby.
* [WSGI](http://legacy.python.org/dev/peps/pep-3333/) for Python.
```

CC @caffinatedmonkey

**Comment by srawlins** [comment]
This is curious behavior. Basically, we're treating all content determined to be within one list item as a block, as the same kind of block as a top-level block. So our behavior that "lists need to be separated by preceding paragraphs by a blank line" is true within list items, and without. However this is not how most parsers work.

See babelmark [for the following](http://johnmacfarlane.net/babelmark2/?text=one%0A*+++list), where most implementations do not produce a list item (although commonmark and GFM do...):

```markdown
one
*   list
```

and [for a list within a list](http://johnmacfarlane.net/babelmark2/?text=*+++one%0A++++*+++list), where most implementations _do_ produce a nested list item:

```markdown
*   one
    *   list
```

I suggest we stick with the "all blocks are the same, even ones nested in list items" policy, and change our behavior of the first example, allowing lists to be directly below paragraphs, without blank lines.

@kevmoo, @munificent , opinions?

**Comment by munificent** [comment]
This is a super annoying corner of Markdown, but I think we'll want to follow CommonMark and GFM if possible.
