### ISSUE TITLE
Can't disable InlineHtmlSyntax

### ISSUE THREAD

**Issue by enyo** [dart-lang/markdown#140]
I have tried using `markdownToHtml` without any extension sets or block/inline syntaxes, but haven't succeeded yet.

I would have thought, that using this code:

``` dart
markdownToHtml(markdownString, extensionSet: ExtensionSet.none);
```

would _not_ enable `FencedCodeBlockSyntax` or the `InlineHtmlSyntax` but they are still enabled.

Am I misunderstanding how that should work, or is this a bug?

**Edit**: I am assuming that `InlineHtmlSyntax` allows for `html` to be left "as is", and I want it to be escaped.

**Comment by srawlins** [comment]
Not sure what you are expecting. Here is some markdown with inline HTML, and it is parsed differently in the two different cases:

```dart
$ cat a.dart
import 'package:markdown/markdown.dart';

void main() {
  print("none:");
  print(markdownToHtml("Hey <em>there</em>", extensionSet: ExtensionSet.none));

  print("commonMark");
  print(markdownToHtml("Hey <em>there</em>"));
}
```

and the execution:

```none
$ dart a.dart
none:
<p>Hey &lt;em>there&lt;/em></p>

commonMark
<p>Hey <em>there</em></p>
```

**Comment by enyo** [comment]
Yes this is the result I would expect, but didn't get. I'll do some more tests on Monday, and check whether it was my fault.

**Comment by enyo** [comment]
Sorry, forgot about it. It's the first thing on my todo list for Monday.

**Comment by enyo** [comment]
I either used it incorrectly or it is fixed now. Thanks!

**Comment by enyo** [comment]
I found the issue! It works fine when there is a string **before** the first occurrence of an HTML tag. But if the first thing in the String is HTML, then the whole string will not be converted with markdown at all:

```dart
markdownToHtml('<script>alert("attack!")</script>  **BOLD**', extensionSet: ExtensionSet.none);
// Result:
// <script>alert("attack!")</script>  **BOLD**

markdownToHtml('**BOLD** <script>alert("attack!")</script>', extensionSet: ExtensionSet.none);
// Result: 
// <p><strong>BOLD</strong> &lt;script>alert("attack!")&lt;/script></p>
```

**Comment by srawlins** [comment]
Ah, so in that case, the line is parsed as an HTML block node, as per [CommonMark](http://spec.commonmark.org/0.27/#html-blocks). Indeed, [babelmark](https://johnmacfarlane.net/babelmark2/?text=%3Cscript%3Ealert(%22attack!%22)%3C%2Fscript%3E++**BOLD**) shows that most parsers accept this as HTML block.

If you want to sanitize your output, you can do it at the Node or HTML output stages.

**Comment by srawlins** [comment]
This issue is now superseded by #161
