### ISSUE TITLE
Table heading does not allow spaces in header lines

### ISSUE THREAD

**Issue by hoylen** [dart-lang/markdown#149]
The implementation of the `TableSyntax` does not handle headings in the same way as GitHub does. Even though the documentation claims it uses GitHub's table syntax.

In the GitHub markdown format, table headings allow spaces between the hyphens and pipes, but this package's implementation does not.

For example, this example from https://help.github.com/articles/organizing-information-with-tables/ is not recognised as a table:

```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

It has to be changed to the following to work:

```
| First Header  | Second Header |
|-------------|-------------|
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```
[md-table-test.txt](https://github.com/dart-lang/markdown/files/648003/md-table-test.txt)

**Comment by srawlins** [comment]
Good catch! Not sure why I made it so strict. Definitely will fix.
