### ISSUE TITLE
Add a way to disable default syntaxes

### ISSUE THREAD

**Issue by enyo** [dart-lang/markdown#152]
In my specific use case, I want to disable the `ImageSyntax`. From what I can see it is added to the `_defaultSyntaxes` List, and there is no way to change this list.

I suggest to add a variable to the constructor named `{List<InlineSyntax> excludeSyntaxes}` that removes unwanted syntaxes

**Comment by srawlins** [comment]
This is a pretty unique ask. And very hard to implement. For example, by default we register 5x TextSyntax objects, and 4x TagSyntaxes. In terms of `s is FooSyntax` checks, there's also the tangle that ImageSyntax extends LinkSyntax.

If you want to sanitize the HTML output, I'd suggest walking the Nodes, or using a library to strip out some of the HTML tags.

**Comment by enyo** [comment]
Ok, that's how I implemented it.
