### ISSUE TITLE
Importing markdown.dart causes application crash.

### ISSUE THREAD

**Issue by meflyup** [dart-lang/markdown#171]
Hi，
my programe run well ,but if I just import the markdwon.dart file without any other additional code ,it throws errors, I am confused  
.
`import 'package:markdown/markdown.dart';`   
and the error msgs   
```
Observatory listening at http://127.0.0.1:51808/
When using Dartium, CHECKED mode is recommended to catch type and assertion warnings, along with more specialized runtime checks in Angular itself for developers.

See https://webdev.dartlang.org/tools/dartium for more information.
Instance of 'MdPreviewer'
EXCEPTION: Error in asset:testpaper/lib/md_previewer/md_previewer.html:0:0
STACKTRACE: 
#0      DebugAppView._rethrowWithContext (package:angular2/src/debug/debug_app_view.dart:332:9)
#1      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:75:7)
#2      ViewAppComponent0.build (package:testpaper/app_component.template.dart:157:18)
#3      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#4      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#5      ViewAppComponentHost0.build (package:testpaper/app_component.template.dart:333:17)
#6      AppView.createHostView (package:angular2/src/core/linker/app_view.dart:188:12)
#7      DebugAppView.createHostView (package:angular2/src/debug/debug_app_view.dart:86:34)
#8      ComponentFactory.create (package:angular2/src/core/linker/component_factory.dart:95:21)
#9      ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:349:38)
#10     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#11     _rootRun (dart:async/zone.dart:1116)
#12     _ZoneDelegate.run (dart:async/zone.dart:676)
#13     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#16     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#17     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:347:12)
#18     coreLoadAndBootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:94:19)
<asynchronous suspension>
#19     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _ZoneDelegate.run (dart:async/zone.dart:675)
#22     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#25     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#26     coreLoadAndBootstrap (package:angular2/src/core/application_ref.dart:89:23)
<asynchronous suspension>
#27     bootstrapStatic (package:angular2/platform/browser_static.dart:67:10)
#28     main (http://localhost:8080/main.dart:11:3)

ORIGINAL EXCEPTION: NoSuchMethodError: Class 'Text' has no instance getter 'parentNode'.
Receiver: Instance of 'Text'
Tried calling: parentNode
ORIGINAL STACKTRACE:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:48)
#2      dbgElm (package:angular2/src/debug/debug_app_view.dart:387:17)
#3      ViewMdPreviewer0.build (package:testpaper/md_previewer/md_previewer.template.dart:102:5)
#4      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#5      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#6      ViewAppComponent0.build (package:testpaper/app_component.template.dart:157:18)
#7      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#8      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#9      ViewAppComponentHost0.build (package:testpaper/app_component.template.dart:333:17)
#10     AppView.createHostView (package:angular2/src/core/linker/app_view.dart:188:12)
#11     DebugAppView.createHostView (package:angular2/src/debug/debug_app_view.dart:86:34)
#12     ComponentFactory.create (package:angular2/src/core/linker/component_factory.dart:95:21)
#13     ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:349:38)
#14     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#15     _rootRun (dart:async/zone.dart:1116)
#16     _ZoneDelegate.run (dart:async/zone.dart:675)
#17     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#20     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#21     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:347:12)
#22     coreLoadAndBootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:94:19)
<asynchronous suspension>
#23     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#24     _rootRun (dart:async/zone.dart:1120)
#25     _ZoneDelegate.run (dart:async/zone.dart:675)
#26     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#29     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#30     coreLoadAndBootstrap (package:angular2/src/core/application_ref.dart:89:23)
<asynchronous suspension>
#31     bootstrapStatic (package:angular2/platform/browser_static.dart:67:10)
#32     main (http://localhost:8080/main.dart:11:3)

ERROR CONTEXT:
Instance of 'DebugContext'

Uncaught Unhandled exception:
EXCEPTION: Error in asset:testpaper/lib/md_previewer/md_previewer.html:0:0
ORIGINAL EXCEPTION: NoSuchMethodError: Class 'Text' has no instance getter 'parentNode'.
Receiver: Instance of 'Text'
Tried calling: parentNode
ORIGINAL STACKTRACE:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      dbgElm (package:angular2/src/debug/debug_app_view.dart:387:17)
#3      ViewMdPreviewer0.build (package:testpaper/md_previewer/md_previewer.template.dart:102:5)
#4      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#5      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#6      ViewAppComponent0.build (package:testpaper/app_component.template.dart:157:18)
#7      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#8      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#9      ViewAppComponentHost0.build (package:testpaper/app_component.template.dart:333:17)
#10     AppView.createHostView (package:angular2/src/core/linker/app_view.dart:188:12)
#11     DebugAppView.createHostView (package:angular2/src/debug/debug_app_view.dart:86:34)
#12     ComponentFactory.create (package:angular2/src/core/linker/component_factory.dart:95:21)
#13     ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:349:38)
#14     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#15     _rootRun (dart:async/zone.dart:1116)
#16     _ZoneDelegate.run (dart:async/zone.dart:675)
#17     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#20     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#21     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:347:12)
#22     coreLoadAndBootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:94:19)
<asynchronous suspension>
#23     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#24     _rootRun (dart:async/zone.dart:1120)
#25     _ZoneDelegate.run (dart:async/zone.dart:675)
#26     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#29     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#30     coreLoadAndBootstrap (package:angular2/src/core/application_ref.dart:89:23)
<asynchronous suspension>
#31     bootstrapStatic (package:angular2/platform/browser_static.dart:67:10)
#32     main (http://localhost:8080/main.dart:11:3)

ERROR CONTEXT:
Instance of 'DebugContext'

#0      DebugAppView._rethrowWithContext (package:angular2/src/debug/debug_app_view.dart:332:9)
#1      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:75:7)
#2      ViewAppComponent0.build (package:testpaper/app_component.template.dart:157:18)
#3      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#4      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#5      ViewAppComponentHost0.build (package:testpaper/app_component.template.dart:333:17)
#6      AppView.createHostView (package:angular2/src/core/linker/app_view.dart:188:12)
#7      DebugAppView.createHostView (package:angular2/src/debug/debug_app_view.dart:86:34)
#8      ComponentFactory.create (package:angular2/src/core/linker/component_factory.dart:95:21)
#9      ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:349:38)
#10     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#11     _rootRun (dart:async/zone.dart:1116)
#12     _ZoneDelegate.run (dart:async/zone.dart:675)
#13     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#16     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#17     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:347:12)
#18     coreLoadAndBootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:94:19)
<asynchronous suspension>
#19     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _ZoneDelegate.run (dart:async/zone.dart:675)
#22     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#25     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#26     coreLoadAndBootstrap (package:angular2/src/core/application_ref.dart:89:23)
<asynchronous suspension>
#27     bootstrapStatic (package:angular2/platform/browser_static.dart:67:10)
#28     main (http://localhost:8080/main.dart:11:3)

```
the dart version is  
`Dart VM version: 1.23.0 (Fri Apr 21 03:13:00 2017) on "windows_x64"`
thanks.

**Comment by srawlins** [comment]
This stack trace has 0 lines from the markdown package. You'll have to provide some context, code, or evidence, that you the markdown package is causing a problem.

**Comment by dani-gallegos** [comment]
I have the same problem. With the default web-angular template from  https://github.com/google/stagehand, and after adding the markdown dependency and the import: import 'package:markdown/markdown.dart';

The program gives the error: 

Observatory listening at http://127.0.0.1:49632/
EXCEPTION: type 'Text' is not a subtype of type 'Node' of 'node' where
  Text is from package:markdown/src/ast.dart
  Node is from dart:html

STACKTRACE: 
#0      Node.append (dart:html:30264)
#1      ViewTodoListComponent0.build (package:untitled2/src/todo_list/todo_list_component.template.dart:123:22)
#2      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#3      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#4      ViewAppComponent0.build (package:untitled2/app_component.template.dart:92:17)
#5      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#6      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#7      ViewAppComponentHost0.build (package:untitled2/app_component.template.dart:245:17)
#8      AppView.createHostView (package:angular2/src/core/linker/app_view.dart:188:12)
#9      DebugAppView.createHostView (package:angular2/src/debug/debug_app_view.dart:86:34)
#10     ComponentFactory.create (package:angular2/src/core/linker/component_factory.dart:95:21)
#11     ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:349:38)
#12     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#13     _rootRun (dart:async/zone.dart:1116)
#14     _ZoneDelegate.run (dart:async/zone.dart:675)
#15     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#16     _CustomZone.run (dart:async/zone.dart:1001)
#17     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#18     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#19     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:347:12)
#20     coreLoadAndBootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:94:19)
<asynchronous suspension>
#21     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _ZoneDelegate.run (dart:async/zone.dart:675)
#24     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#25     _CustomZone.run (dart:async/zone.dart:1001)
#26     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#27     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#28     coreLoadAndBootstrap (package:angular2/src/core/application_ref.dart:89:23)
<asynchronous suspension>
#29     bootstrapStatic (package:angular2/platform/browser_static.dart:67:10)
#30     main (http://localhost:63342/untitled2/web/main.dart:9:3)

ORIGINAL EXCEPTION: type 'Text' is not a subtype of type 'Node' of 'node' where
  Text is from package:markdown/src/ast.dart
  Node is from dart:html


  (anonymous function)	
Uncaught Unhandled exception:
type 'Text' is not a subtype of type 'Node' of 'node' where
  Text is from package:markdown/src/ast.dart
  Node is from dart:html

#0      Node.append (dart:html:30264)
#1      ViewTodoListComponent0.build (package:untitled2/src/todo_list/todo_list_component.template.dart:123:22)
#2      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#3      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#4      ViewAppComponent0.build (package:untitled2/app_component.template.dart:92:17)
#5      AppView.create (package:angular2/src/core/linker/app_view.dart:180:12)
#6      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:73:26)
#7      ViewAppComponentHost0.build (package:untitled2/app_component.template.dart:245:17)
#8      AppView.createHostView (package:angular2/src/core/linker/app_view.dart:188:12)
#9      DebugAppView.createHostView (package:angular2/src/debug/debug_app_view.dart:86:34)
#10     ComponentFactory.create (package:angular2/src/core/linker/component_factory.dart:95:21)
#11     ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:349:38)
#12     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#13     _rootRun (dart:async/zone.dart:1116)
#14     _ZoneDelegate.run (dart:async/zone.dart:675)
#15     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#16     _CustomZone.run (dart:async/zone.dart:1001)
#17     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#18     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#19     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:347:12)
#20     coreLoadAndBootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:94:19)
<asynchronous suspension>
#21     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:320:26)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _ZoneDelegate.run (dart:async/zone.dart:675)
#24     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:175:21)
#25     _CustomZone.run (dart:async/zone.dart:1001)
#26     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:304:23)
#27     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:318:10)
#28     coreLoadAndBootstrap (package:angular2/src/core/application_ref.dart:89:23)
<asynchronous suspension>
#29     bootstrapStatic (package:angular2/platform/browser_static.dart:67:10)
#30     main (http://localhost:63342/untitled2/web/main.dart:9:3)
  (anonymous function)

**Comment by srawlins** [comment]
OK I've made a `web-angular` template app myself now, but I need to know where you are importing `package:markdown/markdown.dart`. I suspect its a namespace collision, since `Text` is provided by both markdown, and `dart:html`. What if you `import 'package:markdown/markdown.dart' as md;`?

**Comment by srawlins** [comment]
This is caused by Angular's template generation. You should be able to avoid it by importing markdown under a namespace. Angular bug: https://github.com/dart-lang/angular/issues/529.

**Comment by dani-gallegos** [comment]
Yes it's a name collission, after importing with an alias, everything works. Thank you for the tip.
