### ISSUE TITLE
Match github emoji support

### ISSUE THREAD

**Issue by isoos** [dart-lang/markdown#175]
Github supports a lot of emojis: https://gist.github.com/rxaviers/7360908

Original request by @pauldemarco at https://github.com/dart-lang/pub-dartlang-dart/issues/326.

**Comment by srawlins** [comment]
I agree. We should support this. Tricky though...

It's not part of the GFM Spec though... e.g. questions: are emojis supported in list items (certainly yes), blockquotes (yes?), code blocks (no?), ...

And where do we source the images? Would we need to see a license? What about just using the UTF Emojis? Is there a mapping from `:thing:` to the HTML entity name? Are they always the same?

**Comment by isoos** [comment]
This suggests that UTF emojis could be just fine: http://www.unicode.org/Public/emoji/5.0/
This is one mapping to start with, not sure of its original source: https://github.com/markdown-it/markdown-it-emoji/tree/master/lib/data

**Comment by isoos** [comment]
A good source of useful links from here: https://news.ycombinator.com/item?id=15947920
- https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb
- https://github.com/milesj/emojibase/blob/master/src/resources/shortcodes.js
- https://github.com/muan/emojilib/blob/master/emojis.json

**Comment by srawlins** [comment]
Thanks so much, @isoos!!! I see that:

* the gist has no license ☹️ 
* the JavaScript file is JavaScript ☹️ 
* the emojilib/emojis.json is MIT! 😄

**Comment by srawlins** [comment]
And in answer to my question about spec, here's what happens in a GitHub comment box:

* emoji in list item: `* :smile:`
  * :smile:
* emoji in blockquote: `> :smile:`
  > :smile:
* emoji in code block: ` ``` :smile:``` `
  ```
  :smile:
  ```
* emoji in header: `# header :smile:`
  * # Header :smile:
* emoji in link text: `[:smile:](http://www.unicode.org/Public/emoji/5.0/)` - [:smile:](http://www.unicode.org/Public/emoji/5.0/)
* emoji in inline code: `:smile:` - `:smile:`
* emoji in reference link: `[ref :smile:]` - [ref :smile:]

So it basically works like other inline elements 😺 

[ref :smile:]: http://www.unicode.org/Public/emoji/5.0/
