### ISSUE TITLE
Support short-hand anchor footnotes

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/markdown#178]
I don't know what the technical name is, but this:

<img width="182" alt="screen shot 2017-10-20 at 8 24 23 pm" src="https://user-images.githubusercontent.com/168174/31847669-b03eafca-b5d4-11e7-99bc-6bffb136ecab.png">

Shows up fine on Github, but not on pub, as a result.

**Comment by srawlins** [comment]
Can you expand on this? Do you just mean that, if I use:

```markdown
[`pubspec.yaml`][pubspec]
```

in markdown, and there is no `[markdown]` reference id in the document, then markdown should next... look in the directory where the markdown document is found, and if it sees... `pubspec` with a known extension, like `pubspec.yaml`, then it links to... where? `<a href="pubspec.yaml">`? Does it look for files in subdirectories?

This sounds like a real hair ball.

**Comment by matanlurey** [comment]
No, there is a reference in the document, it just doesn't work :)

**Comment by srawlins** [comment]
There is support for reference links. Can you give an example?

**Comment by matanlurey** [comment]
Can't reproduce. I suck.
