### ISSUE TITLE
ExtensionSet.gitHub doesn't include ID extensions as documented

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/markdown#185]
The [README](https://github.com/dart-lang/markdown/blob/master/README.md#extension-sets) says that ExtensionSet.gitHub includes the extensions `const SetextHeaderWithIdSyntax()` and `const HeaderWithIdSyntax()`, but it doesn't seem to: https://github.com/dart-lang/markdown/blob/master/lib/src/extension_set.dart#L10.

**Comment by kevmoo** [comment]
My fault in https://github.com/dart-lang/markdown/commit/cfbadaee724c5db5a1fa8ff46e4f47259c59b508

**Comment by srawlins** [comment]
Ugh, yeah this is annoying. Basically, GFM is a well-specified Markdown, but GitHub itself doesn't follow the spec, as it _does_ add header anchors. Do we have an `ExtensionSet.gitHubTheWebsite` and an `ExtensionSet.gitHubFlavored`? Honest question. We want GFM proper for the JSON spec tests, but we also just want to provide the most useful ExtensionSet out of the box.

**Comment by kevmoo** [comment]
Why not both?

Should be easy to clarify in documentation. One aligns w/ the standard. One
aligns w/ what we see on the site?

**Comment by srawlins** [comment]
Yeah that's what I'm in favor of. Are my names ok or dumb? :)

**Comment by kevmoo** [comment]
Maybe just gitHubWeb?

...and just give LOTs of comments linking to the spec, etc
