### ISSUE TITLE
create a public constructor for ExtensionSet

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/markdown#186]
It would be nice if extensions by other packages (e.g. dartdoc) could make use of ExtensionSet.

`new ExtensionSet.from(ExtensionSet.gitHub, inline: [new MoreStuff()], block: [new MoreStuffBlock()])`

A public constructor that could do something like this would let package specific extensions build on those provided by markdown without a lot of boilerplate.

**Comment by srawlins** [comment]
Fixed in 1.1.0
