### ISSUE TITLE
travis failing 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/markdown#191]
https://travis-ci.org/dart-lang/markdown/builds/323208411

1.23, 1.24, and 2.0-dev for a while now

Zero clue...

**Comment by kevmoo** [comment]
CC @srawlins

**Comment by kevmoo** [comment]
Here's the fun:

https://travis-ci.org/dart-lang/markdown/builds/325229352

`--reporter expanded` - fine
`--reporter compact` - broken

**Comment by srawlins** [comment]
Kevin fixed this via #197 and #200. Thanks!
