### ISSUE TITLE
Github Flavored Markdown extended autolinks unsupported

### ISSUE THREAD

**Issue by dudeofawesome** [dart-lang/markdown#201]
[The Github Flavored Markdown spec extends CommonMark's autolinks to support links without `<...>` surrounding them.](https://github.github.com/gfm/#autolinks-extension-)

It appears that the current GFM extension set does not include support for this.
![image](https://user-images.githubusercontent.com/1683595/34742665-ccf59830-f53b-11e7-9224-0da2ea073909.png)

Raw links were passed on before in #33, but that was due to them [not being a part of the CommonMark spec](http://spec.commonmark.org/0.24/#autolinks).

Would this project be open to a PR to add support for this?

**Comment by srawlins** [comment]
Yeah we should support them in GFM. Should not be hard. They have 11 specs for "Autolinks (extension)" and we pass 0 of them :laughing: .
