### ISSUE TITLE
md.Document parses the & and < symbols as HTML instead of raw text

### ISSUE THREAD

**Issue by DaveShuckerow** [dart-lang/markdown#211]
This caused https://github.com/flutter/flutter_markdown/issues/42.  Since Document parses Markdown into an AST, it shouldn't be creating HTML-specific text entities.  Doing this makes it impossible to use the parser to create non-HTML representations of Markdown, including Flutter widgets, without hacking in style overrides.

Is it possible to adjust Document to produce a proper AST that we can render to HTML or other representations separately?

**Comment by kevmoo** [comment]
CC @srawlins

**Comment by srawlins** [comment]
Can you give an example of input, output, and expected output?

**Comment by srawlins** [comment]
This is unfortunate, the CommonMark spec does not really accommodate for this ([Raw HTML](http://spec.commonmark.org/0.28/#raw-html) and [Entity and numerical character references](http://spec.commonmark.org/0.28/#entity-and-numeric-character-references) specs).

The CommonMark dingus [produces AST](
http://spec.commonmark.org/dingus/?text=hey%20%26copy%3B%20you%0A%0Athis%20%3Cem%3Eis%3C%2Fem%3E%20great) for the following input:

```markdown
hey &copy; you

this <em>is</em> great
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <text>hey </text>
    <text>©</text>
    <text> you</text>
  </paragraph>
  <paragraph>
    <text>this </text>
    <html_inline>&lt;em&gt;</html_inline>
    <text>is</text>
    <html_inline>&lt;/em&gt;</html_inline>
    <text> great</text>
  </paragraph>
</document>
```

The `&copy;` is _completely_ swallowed, and not available in the AST, and the HTML is wrapped in `<html_inline>` nodes, but still parsed, so any tool trying to render into a different output still needs to _unparse_ the contents. 😞 

I feel you though; I'd be open to guarding inline HTML and HTML entities behind a flag, say a bool parameter on Document.

**Comment by Hixie** [comment]
Why is this a problem? Can't we just say that markdown includes HTML character reference syntax?

**Comment by Hixie** [comment]
I misunderstood the problem. It's not an issue that "`&copy;`" gets interpreted as a copyright symbol, that's fine, it just means Markdown includes named character reference entities. The problem is that `<` gets turned into `&lt;` in the _output_.

**Comment by srawlins** [comment]
Right, that makes sense. markdown_flutter shouldn't have to write tooling to unparse `&lt;` into `<`.
