### ISSUE TITLE
Publish 2.0.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/markdown#212]
- [ ] Validate SDK docs
  - [x] Fix https://github.com/dart-lang/markdown/issues/213
  - [x] Find root cause of `[operator []]` break w/ dartdoc - https://github.com/dart-lang/markdown/issues/216

**Comment by srawlins** [comment]
Lemme fix #213 first... hopefully today.

**Comment by kevmoo** [comment]
> Lemme fix #213 first... hopefully today.

👍

**Comment by kevmoo** [comment]
@srawlins – sadly, the `[operator []]` is still broken.

Not sure why...

@jcollins-g added validation for it in dartdoc.

**Comment by kevmoo** [comment]
Sorry. I plugged markdown at head against dartdoc and it broke links.

**Comment by kevmoo** [comment]
..still broken means ecrn after you fixed that last issue

**Comment by westy92** [comment]
It looks like #216 has been closed! :tada:

**Comment by kevmoo** [comment]
@srawlins ? 😁

**Comment by srawlins** [comment]
Bueller? Bueller?

Jeez can't a guy work on some P0s every now and then.

**Comment by kevmoo** [comment]
@srawlins I can do it, too. 😄
