### ISSUE TITLE
Support nested brackets in link syntax

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/markdown#213]
This seems to work in [most parsers](https://babelmark.github.io/?text=Sample+link+%5Bto+fun+things%5D(http%3A%2F%2Fnice.com)%0A%0AAnother+link+to+%5Bsomething+else+%5B%5D%5D(http%3A%2F%2Ffoo.com)%0A)

```markdown
Sample link [to fun things](http://nice.com)

Another link to [something else []](http://foo.com)
```

But not ours. Blocking shipping v2

**Comment by kevmoo** [comment]
Yup

**Comment by srawlins** [comment]
This is covered by specs [#483](http://spec.commonmark.org/0.28/#example-483), [#491](http://spec.commonmark.org/0.28/#example-491), and [#499](http://spec.commonmark.org/0.28/#example-499).
