### ISSUE TITLE
Add support for line breaks

### ISSUE THREAD

**Issue by KevinTheGray** [dart-lang/markdown#214]
I am seeing the following issue with `flutter_markdown`, and was told it's an issue with this dependency.   `flutter_markdown` issue filed here: https://github.com/flutter/flutter_markdown/issues/40

Maybe I'm missing something, but I don't see a way to add line breaks where wanted.  A lot of Markdown supports this with the following rule: "To force a line return, place two empty spaces at the end of a line."  

I can get a maximum of one new line, after that, they seem to collapse.  I'd like to have something like
```
Hello
  
  
  
There are three lines of space above this
```

**Comment by kevmoo** [comment]
@KevinTheGray – is this something that we do differently? We try hard to align w/ CommonMark

Try it here: https://babelmark.github.io/

**Comment by lrhn** [comment]
[Commonmark](http://spec.commonmark.org/0.28/#hard-line-breaks) says that two spaces only introduce a hard line break when not at the end of a block, so I think it's working as intended.

Implementations are more likely to see `\` on a line by itself as part of a block, even though they *probably* shouldn't. I'd use no-break spaces instead of empty lines.

**Comment by srawlins** [comment]
Oh I see, you have "blank" lines that consist only of two spaces. `\n` &nbsp; ` ` &nbsp; ` ` &nbsp; `\n`.

Yeah looks like CommonMark only generates one paragraph, like we do. If we're interpreting this wrong, can you paste your input, output, and expected output?

**Comment by KevinTheGray** [comment]
thanks all.  I'm going to review the Commonmark spec to review my options, and I'll come back to this issue shortly.

**Comment by KevinTheGray** [comment]
closing this because I don't believe it's an issue with this package, and needs to be resolved in the flutter_markdown repo
