### ISSUE TITLE
Cannot escape backtick within inline code using double backtick syntax

### ISSUE THREAD

**Issue by droidery** [dart-lang/markdown#249]
Some inline code needs to display a backtick, but this library doesn't handle backtick escapes. The standard way is to wrap the inline code in two backticks (instead of one), then you can use backticks within the inline code.

Example: 
\`\`List\`1\`\`  ->  ``List`1``

Reference with more examples https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown

**Comment by srawlins** [comment]
This works for me:

```none
$ dart bin/markdown.dart --version
2.0.3
$ dart bin/markdown.dart 
``List`1``
<p><code>List`1</code></p>
```

**Comment by droidery** [comment]
Thanks for checking, I wasn't adding the extra spacing required when you want a backtick at the start. Working perfectly now!

**Comment by srawlins** [comment]
Ah, curious. Thanks for following up!
