### ISSUE TITLE
Bad HTML escaping for inlined content

### ISSUE THREAD

**Issue by isoos** [dart-lang/markdown#255]
Markdown: `**\<your project root>ios/**`
Rendered: `<p><strong><your project root>ios/</strong></p>`
Should be: `<p><strong>&lt;your project root&gt;ios/</strong></p>`

**Comment by srawlins** [comment]
The bug is actually that the `>` _is_ escaped. CommonMark specifies that inline HTML should not be escaped.

https://spec.commonmark.org/0.29/#raw-html

> Text between < and > that looks like an HTML tag is parsed as a raw HTML tag and will be rendered in HTML without escaping.

The issue of the `>` being escaped was introduced in https://github.com/dart-lang/markdown/commit/22f647d75e772c3083cd5c41410afeff52d5b2dc.

**Comment by srawlins** [comment]
(Rather, its not escaped in your example, but when I run it locally, it escapes the `>`, since we haven't released https://github.com/dart-lang/markdown/commit/22f647d75e772c3083cd5c41410afeff52d5b2dc.)

**Comment by srawlins** [comment]
Fixed by #256

**Comment by srawlins** [comment]
Fix pushed in markdown 2.1.0.

**Comment by isoos** [comment]
Thanks!
