### ISSUE TITLE
encodeHtml does not get considered inside any BlockSynatx

### ISSUE THREAD

**Issue by IchordeDionysos** [dart-lang/markdown#261]
`encodeHtml` is not considered for example for inside the `CodeBlockSyntax` leading to any `<` being escaped inside of `flutter_markdown` which displays it as normal.

For example here https://github.com/dart-lang/markdown/blob/master/lib/src/block_parser.dart#L401 it is escaped nonetheless of this flag.
<img width="384" alt="Screenshot 2019-09-20 at 16 08 22" src="https://user-images.githubusercontent.com/10195482/65333512-f27d1c00-dbc0-11e9-9a87-13f3441ff351.png">

**Comment by srawlins** [comment]
Thanks for the bug report!

**Comment by srawlins** [comment]
Fix pushed in markdown 2.1.0.
