### ISSUE TITLE
v 2.1.0 does not preserve whitespace in <pre> blocks

### ISSUE THREAD

**Issue by keertip** [dart-lang/markdown#263]
Upgraded to 2.1.0 from 2.0.3 and see a test failure in dartdoc with text like

`Sample class [String]\n<pre> A\n B\n</pre>`
 
markdown removes the whitespace before `A` and `B`, using `HtmlRenderer().render`.

**Comment by srawlins** [comment]
What did that source use to render? What does it render now? Using the command-line tool, it looks like it just puts the source between `<p>` and `</p>`, w/o parsing any markdown between:

```none
$ dart bin/markdown.dart
Sample class [String]\n<pre> A\n B\n</pre>^D
<p>Sample class [String]\n<pre> A\n B\n</pre></p>
```

**Comment by keertip** [comment]
Passing in a node that's text `<pre>\n A\n B\n</pre>`,  get back string `<pre>A\nB\n</pre>`

From the test
```
 Expected: '<p>Sample class <code>String</code></p><pre class="language-dart">  A\n'
              '   B\n'
              '</pre>'
    Actual: '<p>Sample class <code>String</code></p><pre class="language-dart">A\n'
              'B\n'
              '</pre>'
     Which: is different.
            Expected: ... age-dart">  A\n   B\ ...
              Actual: ... age-dart">A\nB\n</pr ...
                                    ^
             Differ at offset 66
```
