### ISSUE TITLE
Horizontal ellipsis(…) is not considered as valid punctuation causes styling as bold failed

### ISSUE THREAD

**Issue by shihchanghsiungsonos** [dart-lang/markdown#267]
The punctuation characters list in _DelimiterRun does not include Horizontal ellipsis(…) as valid punctuation. This causes the styling as bold failed.

Example: If I try to styling as bold in below format:

"Connecting dot \*\*A\*\*\* to \*\*B\*\*\*…"

It shows

"Connecting dot **A*** to \*\*B\*\*\*…"

If I change the string with three comma:

"Connecting dot \*\*A\*\*\* to \*\*B\*\*\*..."

Then it does the styling correctly:

"Connecting dot **A*** to **B***..."

Here are the screenshots:

Using Horizontal ellipsis(…):
<img width="414" alt="Pic1" src="https://user-images.githubusercontent.com/44383755/67607240-ad588680-f738-11e9-948d-6ef55594ed15.png">

Using three comma:
<img width="412" alt="pic2" src="https://user-images.githubusercontent.com/44383755/67607253-b184a400-f738-11e9-981f-7176c899f7c3.png">

**Comment by srawlins** [comment]
What version of the Dart Markdown package are you using? This works for me at HEAD:

```none
$ dart bin/markdown.dart 
"Connecting dot **A*** to **B***…"
<p>"Connecting dot <strong>A</strong>* to <strong>B</strong>*…"</p>
```

and at dart-lang.github.io/markdown.

**Comment by shihchanghsiungsonos** [comment]
We are using flutter_markdown plugin version 0.3.0.

**Comment by srawlins** [comment]
Perhaps the version of the markdown package is old in flutter_markdown 0.3.0. I'd open an issue over there.

**Comment by shihchanghsiungsonos** [comment]
@srawlins, thanks for the follow up.

Looks like if the bold block string is ended with "*", then it still works.

If you try this "Connecting dot **A.** to **B.**…", then you will see the issue even at dart-lang.github.io/markdown.

If I try the same string at https://markdown-it.github.io/, it shows the result correctly.

Thanks!

**Comment by srawlins** [comment]
Ah yes, I can see it now. The relevant text in the CommonMark spec is:

> A punctuation character is an ASCII punctuation character or anything in the general Unicode categories Pc, Pd, Pe, Pf, Pi, Po, or Ps.

This results in the longest regex ever in commonmark.js:

https://github.com/commonmark/commonmark.js/blob/1f7d09099c20d7861a674674a5a88733f55ff729/lib/inlines.js#L39

**Comment by shihchanghsiungsonos** [comment]
haha! So, we are missing "u2026" in that RegExp?

**Comment by srawlins** [comment]
I see `\u2010-\u2027` in commonmark.js's list. :/


I think we can add this fix. Maybe expensive locally, that huge regex, but we don't parse for punctuation very often.

**Comment by shihchanghsiungsonos** [comment]
> I see `\u2010-\u2027` in commonmark.js's list. :/
> 
> I think we can add this fix. Maybe expensive locally, that huge regex, but we don't parse for punctuation very often.

Ya, i see that too. Thanks!
