### ISSUE TITLE
Screen flashing

### ISSUE THREAD

**Issue by Larpoux** [dart-lang/markdown#273]
When I try to display my 'md' text with ExtensionSet.gitHubWeb, 
- first, flutter display the text without replacing the gitHubWeb tags
- and then the correct html with ~~ and :+1: replaced

It makes the screen flashing.
Can I do something to fix that ?

```dart
final String toto = 
"""
Markdown syntax is much simpler and, overall, <u>more readable</u> than ~~this horrible~~ HTML.

With Markdown you can :
- Put make some words ~~with color~~,__bold__, <u>underline</u> or *italic*
- Put a [link](http://www.canardoux.xyz) to a www page
- ... and many other nice things :+1:
"""
...
SingleChildScrollView
         (
                  child: Html
                  (
                           data: md.markdownToHtml
                            (
                                         toto,
                                         extensionSet: md.ExtensionSet.gitHubWeb,
                            ),
                   ),
         ),
```

**Comment by srawlins** [comment]
That is either a Flutter bug or [flutter_markdown](https://github.com/flutter/flutter_markdown) bug. Are you importing the markdown package directly? If so, please look at  the output  of md.markdownToHtml and report what is wrong with the output.

**Comment by srawlins** [comment]
Please re-open with more details if you think this is a bug with the markdown package.
