### ISSUE TITLE
Emphasis surrounding link with asterisk in the label

### ISSUE THREAD

**Issue by jhass** [dart-lang/markdown#280]
Take the following example:

``` 
*test [some*](link)*
````

most implementations, including the official commonmark dingus, seem to parse this "correctly" to

```
<p><em>test <a href="link">some*</a></em></p>
```

This library fails at it:

```diff
diff --git a/test/original/emphasis_and_strong.unit b/test/original/emphasis_and_strong.unit
index 13a6dd2..1df522d 100644
--- a/test/original/emphasis_and_strong.unit
+++ b/test/original/emphasis_and_strong.unit
@@ -81,3 +81,7 @@ a_b_ a__b__ a*b* a**b**
 _a_b c_d_ __a__b c__d__ *a*b c*d* **a**b c**d**
 <<<
 <p><em>a_b c_d</em> <strong>a__b c__d</strong> <em>a</em>b c<em>d</em> <strong>a</strong>b c<strong>d</strong></p>
+>>> link with asterisk
+*test [some*](link)*
+<<<
+<p><em>test <a href="link">some*</a></em></p>
```
```
INPUT:
'''r
*test·[some*](link)*
'''            
           
EXPECTED:
'''r
<p><em>test·<a·href="link">some*</a></em></p>
'''

GOT:
'''r
<p><em>test·[some</em>](link)*</p>
'''
``` 

I looked a bit at it and frankly I'm not sure how to correctly handle this with the current architecture.

**Comment by srawlins** [comment]
Thanks for the excellent bug report! In terms of the spec, we are not following [Rule 17](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis) of "Emphasis and strong emphasis."

> Inline code spans, links, images, and HTML tags group more tightly than emphasis.

Currently the Dart package respects the broader rule that any time we _can_ close a tag, we do, attempting in the order of most recent openings first. I don't think this is terribly hard to correct.
