### ISSUE TITLE
How to convert HTML syntax to node

### ISSUE THREAD

**Issue by asjqkkkk** [dart-lang/markdown#284]
## data

```
![image](https://user-images.githubusercontent.com/30992818/62850471-84b61880-bd15-11e9-80d7-e2ed87aee4fe.png)


<img width="150" alt="018" src="https://user-images.githubusercontent.com/30992818/65006496-c7cb6300-d935-11e9-839b-0f84c8c1b20b.png"/> 
```

## Useage

```
final m.Document document = m.Document(
        extensionSet: m.ExtensionSet.gitHubFlavored,
      );
      final List<String> lines = data.split(RegExp(r'\r?\n'));
      List<m.Node> nodes = document.parseLines(lines);
```

I got the result is:
```
Tag:p   attr:{}
  Tag:img   attr:{src: https://user-images.githubusercontent.com/30992818/62850471-84b61880-bd15-11e9-80d7-e2ed87aee4fe.png, alt: image}
Text:<img width="150" alt="018" src="https://user-images.githubusercontent.com/30992818/65006496-c7cb6300-d935-11e9-839b-0f84c8c1b20b.png"/> 
```
The second image has not been converted to a node

How should I do? 🤔️
Someone help me please.😊

**Comment by srawlins** [comment]
In your markdown text you have two primary components:

1. a paragraph with a markdown syntax for an image,
2. a raw HTML component, which contains the html syntax for an image.

So what gets output is:

1. an Element for a paragraph tag, which includes one Element for an image tag.
2. a Text node which contains the raw HTML.

This package does not contain any code for _parsing_ raw HTML into a tree of HTML nodes. And there are certainly not matching Markdown nodes for all of the HTML nodes.

Instead, the package sees the raw HTML and says, "ah ha, I can just copy this text here verbatim, into a Text node, to be rendered in HTML; I have no idea what it contains; I cannot parse HTML; but I can include it in the HTML output when this Node tree is rendered to HTML."

**Comment by asjqkkkk** [comment]
ok,  maybe I need to find someway to solve this problem, thank you😄
