### ISSUE TITLE
Custom tag not parsed as element

### ISSUE THREAD

**Issue by liudonghua123** [dart-lang/markdown#285]
I want to do some custom tag process. I have `<avatar size="12" name="tom" />` in markdown file. and I use `document.parseLines` to parse it. I expected to get element with tag `avatar` and some attributes, just like `hr` or `p` standard tag, but it only return a text node.

I go through the code, and find `OtherTagBlockHtmlSyntax`, but it does not parse it as a element.

![image](https://user-images.githubusercontent.com/2276718/79757505-c2604c00-834e-11ea-9b43-b15c092aeb04.png)

How can I achieve this, or I missed something else?

**Comment by srawlins** [comment]
This is the same issue as https://github.com/dart-lang/markdown/issues/284; The markdown package does not include an HTML parser. You'll have to find a separate solution.
