### ISSUE TITLE
HTML Elements are not consistent

### ISSUE THREAD

**Issue by isoos** [dart-lang/markdown#29]
``print(markdownToHtml('<div>\n\n**abc**\n\n</div>\n'));`` does escape the first '<' of the closing DIV and wraps it inside a P element:

````
<div>
<p><strong>abc</strong></p>
<p>&lt;/div></p>
````

Removing 1-1 newlines, and ``print(markdownToHtml('<div>\n**abc**\n</div>\n'));`` does not convert the content to strong:

````
<div>
**abc**
</div>
````

In both cases, the expected output would be something like this:

````
<div>
<p><strong>abc</strong></p>
</div>
````

**Comment by munificent** [comment]
This is working as intended (though it may not be fully compatible with other markdown implementations).

If I get the time to make the package compliant with CommonMark (which didn't exist when I first wrote the package), then this behavior might change. Until then, it's as designed.
