### ISSUE TITLE
README Documentation on Extension sets is out-of-date

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#301]
The documentation on Extension sets in the README is out-of-date. First, the last sentence in the first paragraph in the Extension sets section states:

> "Right now there are two extension sets:"

This is incorrect from two perspectives. First, the current README documentation continues on from this statement and identifies three extension sets, not two. Secondly, the current ExtensionSet class in version 2.1.7 defines four extension sets; ExtensionSet.none, ExtensionSet.commonMark, ExtensionSet.gitHubWeb, and ExtensionSet.gitHubFlavored. The documentation is missing information about the ExtensionSet.gitHubFlavored extension set.

Also, the ExtensionSet.gitHubWeb bullet point says it includes seven extensions. Version 2.1.7 of the package has eight extensions, AutolinkExtensionSyntax is missing from the list.

**Comment by domesticmouse** [comment]
Please feel free to create a PR that fixes this issue =)

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/markdown/pull/308
