### ISSUE TITLE
Fix "Follow Dart file conventions" Issues

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#310]
Fix the Follow Dart file conventions issues identified on [pub.dev score](https://pub.dev/packages/markdown/score) to improve the pub points score of the markdown package.

Follow Dart file conventions:

- 0/10 points: Provide a valid pubspec.yaml
  -  The package description is too short.
- 0/5 points: Provide a valid README.md
  -  Links in `README.md` should be secure. 8 links are insecure.
- 0/5 points: Provide a valid CHANGELOG.md
  -  Links in `CHANGELOG.md` should be secure. 3 links are insecure.

**Comment by srawlins** [comment]
Fixed by #311
