### ISSUE TITLE
markdownToHtml doesn't work for tables

### ISSUE THREAD

**Issue by sgehrman** [dart-lang/markdown#314]
| ssss ssss  | wwwww ddddd |
| :--------: | ----------: |
| this sucks |  this sucks |

// html shows this:

| ssss ssss | wwwww ddddd | | :--------: | ----------: | | this sucks | this sucks |

works fine in markdown view

**Comment by srawlins** [comment]
Please describe steps to reproduce your problem.  Describe the output you expect to see, and the output you see instead. Perhaps show the markdown text you use as input, and the HTML text outputs (expected and actual).

**Comment by NamanShergill** [comment]
> Please describe steps to reproduce your problem. Describe the output you expect to see, and the output you see instead. Perhaps show the markdown text you use as input, and the HTML text outputs (expected and actual).

He did, didn't he? If you run the given table through markdownToHtml you get the broken output. I have been facing this issue as well.

**Comment by srawlins** [comment]
@NamanShergill I don't see any Markdown text that I can try with, nor what the expected output is. OP's description includes a table and an individual line of text which might be a Markdown table source if it was more than a single line long. Could you provide details about the issue you are seeing?

**Comment by NamanShergill** [comment]
> @NamanShergill I don't see any Markdown text that I can try with, nor what the expected output is. OP's description includes a table and an individual line of text which might be a Markdown table source if it was more than a single line long. Could you provide details about the issue you are seeing?

Right, sorry, here's the table in markdown form that GitHub turns into a proper table.

```
| ssss ssss  | wwwww ddddd |
| :--------: | ----------: |
| this sucks |  this sucks |
```

| ssss ssss  | wwwww ddddd |
| :--------: | ----------: |
| this sucks |  this sucks |

**Comment by NamanShergill** [comment]
Just realised that this kind of markdown is part of the github flavoured markdown only. Will check if it works when the extension set is specified to it.

**Comment by NamanShergill** [comment]
Confirmed, this isn't an issue, just need to specify the github extension set.
