### ISSUE TITLE
BlockQuote color is hardcoded in material theme

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/markdown#324]
![image](https://user-images.githubusercontent.com/7407478/94035042-54bbbe80-fdcb-11ea-9c92-d355ad1f774e.png)

![image](https://user-images.githubusercontent.com/7407478/94035113-669d6180-fdcb-11ea-8d80-3d3c7d8e7a0c.png)

**Comment by srawlins** [comment]
Please explain what issue you are facing. You can list the code you used, the expected result, and the actual result.

A note on the issue summary though: The markdown package knows of no "material theme."

**Comment by SwissCheese5** [comment]
You're right, this is meant for flutter_markdown. Sorry for the inconvenience.
