### ISSUE TITLE
Reference Link Unicode Case Fold Doesn't Work In All Cases

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#333]
The markdown package has some errors in supporting Unicode case fold. The [CommonMark example for Unicode case fold](https://spec.commonmark.org/0.29/#example-536) does produce the correct results. But the [GitHub Flavored Markdown example for Unicode case fold](https://github.github.com/gfm/#example-548) produces incorrect results.

```
CommonMark Spec Example 536

[Толпой][Толпой] is a Russian word.

[ТОЛПОЙ]: /url
 ```
correctly produces the following HTML output:
```
<p><a href="/url">Толпой</a> is a Russian word.</p>
```
However, the markdown package produces an incorrect result for the GFM example. The following sample code:
```
GitHub Flavored Markdown Spec Example 548

[ẞ]

[SS]: /url
 
---

import 'package:markdown/markdown.dart';

void main() {
  print(markdownToHtml('[ẞ]\n\n[SS]: /url'));
}
```
Produces the following incorrect HTML output:
```
<p>[ẞ]</p>
```

**Comment by kevmoo** [comment]
This has been fixed in v7 it appears
