### ISSUE TITLE
Reference Link Definition Matching Error

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#334]
The markdown package incorrectly matches reference link labels. Matching is supposed to be performed on normalized strings and not parsed line content.

Both the [CommonMark](https://spec.commonmark.org/0.29/#example-541) and [GitHub Flavored Markdown](https://github.github.com/gfm/#example-553) specifications note that "_...matching is performed on normalized strings, not parsed inline content._"  (click on the document links to go to the examples in the specifications). The example from both specs show the example Markdown input data:

```
[bar][foo\!]

[foo!]: /url
 ```
should produce the following HTML output:
```
<p>[bar][foo!]</p>
```
However, the markdown package does not properly match this reference link label. The following sample code:
```
import 'package:markdown/markdown.dart';

void main() {
  print(markdownToHtml('[bar][foo\!]\n\n[foo!]: /url'));
}
```
Produces the following incorrect HTML output:
```
<p><a href="/url">bar</a></p>
```

**Comment by kevmoo** [comment]
Fixed in v7
