### ISSUE TITLE
Incorrect Parsing of Reference Link Label With Escaped Backslash

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#336]
The markdown package incorrectly parses reference link labels with escaped backslash.

Both the [CommonMark](https://spec.commonmark.org/0.29/#example-546) and [GitHub Flavored Markdown](https://github.github.com/gfm/#example-558) specifications note regarding link labels with brackets an escaped backslash immediately preceding the closing square bracket that "_... in this example ] is not backslash-escaped_"  (click on the document links to go to the examples in the specifications). The example from both specs show the example Markdown input data:

```
[bar\\]: /uri

[bar\\]
 ```
should produce the following HTML output:
```
<p><a href="/uri">bar\</a></p>
```
However, the markdown package does not properly parse this reference link. The following sample code:
```
import 'package:markdown/markdown.dart';

void main() {
  print(markdownToHtml('[bar\\]: /uri\n\n[bar\\]'));
}
```
Produces the following incorrect HTML output:
```
<p>[bar]</p>
```

**Comment by kevmoo** [comment]
Fixed in v7
