### ISSUE TITLE
Incorrect Parsing of Backslash-Escaped Bracketed Text

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#337]
The markdown package incorrectly parses backslash-escaped bracketed text.

Both the [CommonMark](https://spec.commonmark.org/0.29/#example-559) and [GitHub Flavored Markdown](https://github.github.com/gfm/#example-571) specifications note that "_If you just want bracketed text, you can backslash-escape the opening bracket to avoid links_"  (click on the document links to go to the examples in the specifications). The example from both specs show the example Markdown input data:

```
\[foo]

[foo]: /url "title"
 ```
should produce the following HTML output:
```
<p>[foo]</p>
```
However, the markdown package does not properly parse this backslash-escaped bracketed text. The following sample code:
```
import 'package:markdown/markdown.dart';

void main() {
  print(markdownToHtml('\[foo]\n\n[foo]: /url "title"'));
}
```
Produces the following incorrect HTML output:
```
<p><a href="/url" title="title">foo</a></p>
```

**Comment by kevmoo** [comment]
Fixed in v7
