### ISSUE TITLE
Incorrect Parsing of Tables with Escaped Pipes in Cell Content

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#340]
The markdown package incorrectly parses a table with escaped pipes in the cell content.

The [GitHub Flavored Markdown](https://github.github.com/gfm/#example-200) specification note that tables can "_... Include a pipe in a cell’s content by escaping it, including inside other inline spans._"  (click on the document link to go to the example in the specification). The example from the specs show the example Markdown input data:

```
| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
 ```
should produce the following HTML output:
```
<table>
<thead>
<tr>
<th>f|oo</th>
</tr>
</thead>
<tbody>
<tr>
<td>b <code>|</code> az</td>
</tr>
<tr>
<td>b <strong>|</strong> im</td>
</tr>
</tbody>
</table>
```
However, the markdown package does not properly parse this table. The following sample code:
```
import 'package:markdown/markdown.dart';

String data = """
| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
""";

void main() {
  print(markdownToHtml(data, extensionSet: ExtensionSet.gitHubFlavored));
}
```
Produces the following incorrect HTML output:
```
<p>| ------ |
| b <code>|</code> az |
| b <strong>|</strong> im |</p>
```

**Comment by kevmoo** [comment]
I believe this was fixed in v7
