### ISSUE TITLE
publish null-safe package version

### ISSUE THREAD

**Issue by pq** [dart-lang/markdown#351]
It looks like the API is migrated or under-way.

@srawlins: thoughts on publishing?

We'll want this for the linter (https://github.com/dart-lang/linter/issues/2399).

Thanks!

**Comment by srawlins** [comment]
Happy to publish today. I think args has since been published with a null safe version, so I'll take one more pass at unmigrated deps, and publish today.

**Comment by pq** [comment]
Thanks!

https://pub.dev/packages/args/versions/2.0.0-nullsafety.0 👍
