### ISSUE TITLE
PDF rendering

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/markdown#356]
This package appears to be structured in a way that allows output of any form, with HTML being the one existing implemented option.

Would it be possible to implement PDF output, using [`package:pdf`](https://pub.dev/packages/pdf), perhaps?

**Comment by srawlins** [comment]
Very cool that there is a PDF-rendering package. We have no plans to add a dependency to this package though, in order to render Markdown source to PDF output. I think a separate package would be best.
