### ISSUE TITLE
Multiline quote with extra spaces

### ISSUE THREAD

**Issue by isoos** [dart-lang/markdown#358]
Version: `markdown 3.0.0`
Original report for pub-dev: https://github.com/dart-lang/pub-dev/issues/4552

User reported that the following multiline quote with new line and leading spaces is parsed incorrectly:

```
> lorem
       ipsum
```

The expectation is that both lines will get parsed as the content of the same quote. Instead, the second line is getting parsed as a code block.

**Comment by isoos** [comment]
@srawlins: Thanks for fixing this! Is there any estimate when this will be released?

**Comment by srawlins** [comment]
Just released as markdown 5.0.0
