### ISSUE TITLE
Change color of the code block backround

### ISSUE THREAD

**Issue by N1ght-Fury** [dart-lang/markdown#360]
Hey! How can i change backround color of the code block from white to grey? Here is my marrkdown example:

![image](https://user-images.githubusercontent.com/44553433/109414766-ad6c3480-79c5-11eb-96fc-9d6c446ceeb8.png)

When i run the following command:

![image](https://user-images.githubusercontent.com/44553433/109414745-9594b080-79c5-11eb-9d27-62cee3d769c0.png)

This is the output i get:

```
<p>Markdown is the <strong>best</strong>!</p>
<ul>
<li>It has lists.</li>
<li>It has <a href="http://dart.dev">links</a>.</li>
<li>It</li>
</ul>
<pre><code>test
123456
</code></pre>
```

I want my code blocks to look like on the web version (https://dart-lang.github.io/markdown/), like in the picture, with the grey backround.

![image](https://user-images.githubusercontent.com/44553433/109414787-cf65b700-79c5-11eb-8165-b5babf86a7fe.png)

How can i do that? Is it possible?

Thanks in advance!

**Comment by srawlins** [comment]
You will have to apply a CSS style to all `<pre>` or all `<code>` tags in the web page in which you render this HTML.

If that highlights undesirable things, you can put all rendered Markdown into a specific container like `<div class="markdown">` and then apply those CSS styles to tags under `div.markdown`. There is no solution that the markdown Dart package can provide.

**Comment by N1ght-Fury** [comment]
Okay thank you so much! Will try to do it that way

How does it work on web version tho? The same way as you explained?

**Comment by srawlins** [comment]
Yes I think that site uses some CSS to style the pre or the code tags.
