### ISSUE TITLE
Allow providing a parameter to ignore case sensitivity in RegExp when extending InlineSyntax

### ISSUE THREAD

**Issue by NamanShergill** [dart-lang/markdown#367]

**Comment by srawlins** [comment]
It sounds like you are looking for an extra parameter on the InlineSyntax constructor? That sounds perfectly reasonable.

**Comment by NamanShergill** [comment]
> It sounds like you are looking for an extra parameter on the InlineSyntax constructor? That sounds perfectly reasonable.

Yep! RegExp can have a case sensitive and a couple other parameters passed to it which cannot be passed to the InlineSyntax constructor currently.
