### ISSUE TITLE
square brackets inside of inline code should be left alone

### ISSUE THREAD

**Issue by herhut-ggl** [dart-lang/markdown#37]
I want to write a comment that contains an example with a list literal like

`const ["foo", "bar"]`

which should render as shown by the github markdown parser here. Instead, the square brackets disappear.

**Comment by munificent** [comment]
How are you indicating the inline code? Are you using backticks, a separate code block, or a fenced code block?

**Comment by herhut-ggl** [comment]
IIRC the same way as it is done in the report, with backticks.

**Comment by munificent** [comment]
I can't seem to repro it right now. This:

```markdown
code `const ["foo", "bar"]` here
```

Gets formatted to:

```html
<p>code <code>const ["foo", "bar"]</code> here</p>
```

Which looks right to me. If you come up with a way to reproduce this, let me know and I'll re-open the bug.
