### ISSUE TITLE
Support for upload local images 

### ISSUE THREAD

**Issue by marta-blazquez** [dart-lang/markdown#380]
It looks like using this library we can't load any images from the local folder; we can use network urls for images instead of local images reference from the folder.

There is some way to be able to load the local images and avoid to use the URL of the image from cdn? 

Thank you

**Comment by srawlins** [comment]
This package actually doesn't load images from anywhere. Have you filed this question against the wrong repo, perhaps?

**Comment by marta-blazquez** [comment]
Oh, sorry, let me try to explain better my problem. I have create some mardown files, and need to parse it into HTML. 

My markdown file has images, and I need to apply some style, so I have changed this: 

![](./images/migration-hub.png)

for this: 

<img src="./images/migration-hub.png" alt="" width="32" height="32"/>

but, by using this library It looks like we can’t load any images from the folder. Is there any way to uploading local images? 

Thank you

**Comment by srawlins** [comment]
Sorry, your message has some blank spots and a broken image. Can you put code samples in backticks? See https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by marta-blazquez** [comment]
I try again: 

My markdown file has images, and I need to apply some style, so I have changed this:

```
![](./images/migration-hub.png)

```
to this:

```
<img src="./images/migration-hub.png" alt="" width="32" height="32"/>

```
But using this library It looks like we can’t load any images from the folder. Is there any way to uploading local images? or the only way is to upload images is using url like:

```
<img src=“https://www.w3schools.com/images/lamp.jpg” alt=“Lamp” width=“32” height=“32">
```

Thank you

**Comment by srawlins** [comment]
The markdown library provides no uploading mechanism.

**Comment by huang12zheng** [comment]
That's a good question.
My idea is to modify the [Custom syntax extensions](https://github.com/dart-lang/markdown#:~:text=Custom%20syntax%20extensions), and add it to inlineSyntaxes on InlineParser.


in other word, There are these changes:
* Default
```
parse ![](./images/migration-hub.png) => DefaultNode
```
* Custom
```
parse ![](./images/migration-hub.png) => InlineLink with destination is http://domain/images/migration-hub.png
```

In the end, this is just my idea, no actual example. But I think that's what you're asking and want.
@marta-blazquez
