### ISSUE TITLE
Modify font size of paragraphs

### ISSUE THREAD

**Issue by antonio-gravity** [dart-lang/markdown#381]
Hi everyone. We are having trouble modifying the font size of the various elements. If someone could give me an example of how they have managed to modify properties such as the font size, the space between lines or the space between elements, I would appreciate it. I have looked for documentation and examples but have had no luck. Attached screen of the point where I am and where I want to go. I have the problem especially with the size of the font in the paragraphs.

Thank you!

<img width="428" alt="Captura de pantalla 2021-11-09 a las 14 15 38" src="https://user-images.githubusercontent.com/80257570/140930749-a50e4769-4907-45aa-85b3-fd1acdb0f908.png">

**Comment by srawlins** [comment]
A request for community examples is better served by a site like StackOverflow.

For this specific question, the Dart markdown package (and the Markdown language) do not offer any specific support for text size or styling, except that you may be able to insert raw HTML, if HTML is your desired output. See some examples in the CommonMark spec (a Markdown specification that the Dart markdown package strives to adhere to): https://spec.commonmark.org/0.30/#raw-html
