### ISSUE TITLE
import conflict with Flutter lib

### ISSUE THREAD

**Issue by chrisvidal** [dart-lang/markdown#390]
I am using a Colum with a Text Widget and the markdownToHtml function, and got this error:

any idea to resolve this conflict please?

```
The name 'Text' is defined in the libraries 'package:flutter/src/widgets/text.dart' and 'package:markdown/src/ast.dart (via package:markdown/markdown.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```

**Comment by srawlins** [comment]
The second line of text has the possible resolutions.

> Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

**Comment by chrisvidal** [comment]
well, both library are out my scope, I don't have access to both of them hence I cant do any prefixing as suggested.

**Comment by srawlins** [comment]
The file that imports both "'package:flutter/src/widgets/text.dart' and 'package:markdown/src/ast.dart (via package:markdown/markdown.dart)'" needs to be changed (to [use an import prefix or hide elements](https://dart.dev/guides/language/language-tour#specifying-a-library-prefix)). You can file a bug against whoever owns that file.

**Comment by chrisvidal** [comment]
that's what I thought. Aren't you the owner of the file `'package:markdown/src/ast.dart (via package:markdown/markdown.dart)'`

**Comment by srawlins** [comment]
I am. But I am not the owner of the file which imports it and 'package:flutter/src/widgets/text.dart'.
