### ISSUE TITLE
analysis errors when compiling the markdown package with ddc

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/markdown#40]
When run on the `0.1.4` version of the dev_compiler, I see these errors:

```
severe: [AnalyzerMessage] The getter 'children' is not defined for the class 'Node' (package:markdown/src/inline_parser.dart, line 361, col 10)
severe: [AnalyzerMessage] The getter 'attributes' is not defined for the class 'Node' (package:markdown/src/inline_parser.dart, line 354, col 36)
severe: [AnalyzerMessage] The getter 'text' is not defined for the class 'Node' (package:markdown/src/inline_parser.dart, line 136, col 48)
severe: [AnalyzerMessage] The getter 'children' is not defined for the class 'Node' (package:markdown/src/inline_parser.dart, line 355, col 34)
severe: [AnalyzerMessage] The getter 'attributes' is not defined for the class 'Node' (package:markdown/src/inline_parser.dart, line 353, col 34)
severe: [InvalidSuperInvocation] super call must be last in an initializer list (see http://goo.gl/q1T4BB): super(pattern) (package:markdown/src/inline_parser.dart, line 191, col 9)
severe: [InvalidSuperInvocation] super call must be last in an initializer list (see http://goo.gl/q1T4BB): super(pattern) (package:markdown/src/inline_parser.dart, line 230, col 9)
```

**Comment by devoncarew** [comment]
Once this package merge's in some of the outstanding PR's, we should pull in some ddc diffs from here: https://github.com/dart-lang/markdown/compare/master...radicaled:fix_type_problems.

**Comment by munificent** [comment]
In this case, DDC is pointing out a legitimate issue with the package. `ImageLinkSyntax.createNode()` is assuming `LinkSyntax.createNode()` always returns an `Element` even though it's annotated to return a `Node`. In most cases, that's true, but it's entirely possible for an external `Resolver` passed into the markdown package to return a non-`Element` node. If that happens, `ImageLinkSyntax.createNode()` is going to crash.

I think this only comes into play with markdown like `Some ![image] with no URL`. That shouldn't be valid anyway, so I think the code is just wrong here. We shouldn't support implicit links for images. The right fix is for `ImageLinkSyntax.createNode()` to not go through `super.createNode()`.
