### ISSUE TITLE
Italalic and bold interactions, convert to html the italic format is error

### ISSUE THREAD

**Issue by chifandeyu** [dart-lang/markdown#432]
`String markdown = 'a_bc**d_e**';`
`final html = markdownToHtml(markdown);`
then html is '<p>ah_eh<strong>fa_u</strong>hdf</p>'

**Comment by srawlins** [comment]
Er, I think your example is not right. For example there are no `h`s in the input text.

And just to make sure that I can tell what the output is which you do not like, can you show the raw HTML, rather than HTML which my browser is interpreting.

What output do you expect to see?

**Comment by chifandeyu** [comment]
> Er, I think your example is not right. For example there are no `h`s in the input text.
> 
> And just to make sure that I can tell what the output is which you do not like, can you show the raw HTML, rather than HTML which my browser is interpreting.
> 
> What output do you expect to see?

Thank you for your reply.
I want to convert like that format text:
![image](https://user-images.githubusercontent.com/15946864/169357073-f17cff65-1354-4b1d-9e29-1d85147a827f.png)

**Comment by srawlins** [comment]
Please show the HTML tags that you expect. If I had to guess at what you pasted, it looks like you want the em and strong tags to cross over each other, which is not allowed in HTML.

The Dart markdown package adheres to the CommonMark standard, which would output `<p>a_bc<strong>d_e</strong></p>`. See https://babelmark.github.io/?text=a_bc**d_e**

**Comment by srawlins** [comment]
OK cool, I see what you expect.

Yes the markdown package will not produce that output. I don't know if there is a way in pure markdown to get the output you desire, but you can use inline HTML tags perhaps: `a<em>bc</em>**<em>d</em>e**`.
