### ISSUE TITLE
markdownToHtml doesn't work for strike

### ISSUE THREAD

**Issue by chifandeyu** [dart-lang/markdown#436]
the markdown is "a\~\~bc\~\~d";
I hope can support convert to html "a\<s>bc\</s>d";

**Comment by srawlins** [comment]
Thanks for the report. Please give the code which ran which did not generate what you expected. Also please give what is generated.

Also note that strikethrough syntax is only supported with the GitHub-flavored Markdown extension.

**Comment by chifandeyu** [comment]
> Thanks for the report. Please give the code which ran which did not generate what you expected. Also please give what is generated.
> 
> Also note that strikethrough syntax is only supported with the GitHub-flavored Markdown extension.

I expected result is "a\<del>bc\</del>d"

**Comment by srawlins** [comment]
@chifandeyu 

Please give the code which ran which did not generate what you expected. Also please give what is generated.

Also note that strikethrough syntax is only supported with the GitHub-flavored Markdown extension.
