### ISSUE TITLE
{Ordered,Unordered}ListWithCheckBoxSyntax should allow lists where the first item is not a checkbox

### ISSUE THREAD

**Issue by srawlins** [dart-lang/markdown#448]
GitHub is the spec here, and on GitHub, the following generates a checkbox list, with some items getting checkboxes, even though the first does not have a checkbox:

```markdown
* hello
* [ ] there
```

renders as:

```html
<ul class="contains-task-list">
<li>hello</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox"> there</li>
</ul>
```

The markdown package currently does _not_ parse such input as a list-with-checkboxes.

**Comment by chenzhiguang** [comment]
https://github.github.com/gfm/#task-list-items-extension- says:

> GFM enables the tasklist extension, where an additional processing step is performed on [list items](https://github.github.com/gfm/#list-items).

Maybe we should try to add this additional process on list syntax instead? (parse the captured list items)

**Comment by srawlins** [comment]
Could be. Whatever's easiest, and maintains the mechanism of using `{Ordered,Unordered}ListWithCheckBoxSyntax` in order to enable the syntax.

**Comment by chenzhiguang** [comment]
@srawlins Here we go https://github.com/dart-lang/markdown/pull/450

**Comment by chenzhiguang** [comment]
@srawlins This issue has been fixed already.
