### ISSUE TITLE
Confirm the mark and license for forked code

### ISSUE THREAD

**Issue by Guo-Zhang** [dart-lang/markdown#453]
Hello! I am extending the Dart and Flutter Markdown to implement [MyST Markdown](https://myst-parser.readthedocs.io/en/latest/index.html) by [JupyterBook Project](https://jupyterbook.org/en/stable/index.html).

I have forked the `fenced_code_block_syntax.dart` module to my project. I marked at the top of the file, see:

```
/// Originally based on `package:markdown/src/block_syntaxes/fenced_code_block_syntax.dart` (BSD)
/// https://github.com/dart-lang/markdown/blob/master/lib/src/block_syntaxes/fenced_code_block_syntax.dart
/// See https://github.com/dart-lang/markdown/blob/master/LICENSE for original license.
```

https://github.com/quanttide/flutter-myst-markdown/blob/master/lib/src/block_syntaxes/executive_code_block_syntax.dart

Is this a proper mark for using the code? 

Thanks for your help!

**Comment by srawlins** [comment]
None of us are lawyers here, but if you search around for how to fork open source code, with [our particular license](https://github.com/dart-lang/markdown/blob/master/LICENSE), I think you'll find your answer. No concerns by me.
