### ISSUE TITLE
[Feature Request] Video embedding support for markdown

### ISSUE THREAD

**Issue by studanshu** [dart-lang/markdown#457]
Hi,
Originally markdown does not support video embedding. I was wondering if we can have a new syntax in markdown to support inline video embedding.

For example,
`<vid src="https://www.youtube.com/watch?v=BBAyRBTfsOU" width="500">`
OR
`!![Video Name](https://www.youtube.com/watch?v=BBAyRBTfsOU#500)`

**Comment by srawlins** [comment]
A fun idea.

The dart markdown package is designed to adhere to the commonmark standard, and a few extensions to that standard, like GitHub-flavored Markdown. We won't be defining our own syntaxes, so as to not fragment the Markdown community.

Inline HTML tags should be supported though.

**Comment by jonasfj** [comment]
Let's close this as out-of-scope.

You can totally make `<iframe>`, but things like `dartdoc` and `pub.dev` will run the markdown through an HTML sanitizer that removes anything remotely sketchy.

The classic way to embed youtube videos in markdown is using a thumbnail image that is also a link to vidoe, example: https://gist.github.com/bitsurgeon/acd769ae3236c48a433e0acb11784c2e
