### ISSUE TITLE
Link creation bugs in GitHubWeb-flavored extension

### ISSUE THREAD

**Issue by isoos** [dart-lang/markdown#470]
Original report on `pub-dev`: https://github.com/dart-lang/pub-dev/issues/6126
Markdown version: `6.0.1`

**1. Extra text content after the link closing tag:**
```
dart run markdown --extension-set GitHubWeb
(https://github.com/intel/rohd/issues/129)
<p><a href="https://github.com/intel/rohd/issues/129">https://github.com/intel/rohd/issues/129</a>9)</p>
```

**2. <a> href URL with extra parenthesis, also in the link text content:**
```
dart run markdown --extension-set GitHubWeb
(https://github.com/intel/rohd/issues/129).
<p><a href="https://github.com/intel/rohd/issues/129)">https://github.com/intel/rohd/issues/129)</a>).</p>
```

**Comment by chenzhiguang** [comment]
Fixed.

**Comment by isoos** [comment]
@chenzhiguang @srawlins: any ETA when this (and other fixes) will get released?

**Comment by srawlins** [comment]
I'm hoping within a month.
