### ISSUE TITLE
add a CI check for compatibility with package:flutter_markdown

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/markdown#477]
We should consider adding a CI check for compatibility with `package:flutter_markdown`. They're both imported into google3, and we've had two cases where changes in package:markdown broke package:flutter_markdown; the issues weren't discovered until markdown had been rolled into the sdk, and then that rolled into google3. The sdk roll into google3 is generally delayed, and the change - far upstream in markdown - then has to be reverted, or both it and flutter_markdown updated.

Having a presubmit test here to check against package:flutter_markdown would give us advance awareness of potentially breaking changes.

**Comment by srawlins** [comment]
+1.

I'll note that for major version bumps, rolls into google3 should be preceded by a TGP, and maybe some flutter bot in the SDK.
