### ISSUE TITLE
[BUG] Text selection not working on vertical axis

### ISSUE THREAD

**Issue by awh6al** [dart-lang/markdown#482]
**Steps to Reproduce:**
- Mouse left click
- Slide the mouse back and forth over horizontal axis
- slide the mouse over the vertical axis

**Expected results:**
Select text vertically

**Actual results:**
Selected text stopping to follow the mouse cursor

flutter doctor -v
<details>
<summary>Logs</summary>

[✓] Flutter (Channel master, 3.5.0-12.0.pre.8, on Manjaro Linux 6.0.0-1-MANJARO, locale en_US.utf8)
• Flutter version 3.5.0-12.0.pre.8 on channel master at /opt/flutter-sdk
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 0b451b6dfd (5 days ago), 2022-10-28 12:40:09 -0700
• Engine revision d90e5b7372
• Dart version 2.19.0 (build 2.19.0-347.0.dev)
• DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /opt/android-sdk
• Platform android-33, build-tools 31.0.0
• ANDROID_HOME = /opt/android-sdk
• ANDROID_SDK_ROOT = /opt/android-sdk
• Java binary at: /usr/lib/jvm/default/bin/java
• Java version OpenJDK Runtime Environment (build 18.0.2+0)
• All Android licenses accepted.

[✓] Chrome - develop for the web
• CHROME_EXECUTABLE = /usr/bin/brave

[✓] Linux toolchain - develop for Linux desktop
• clang version 14.0.6
• cmake version 3.24.2
• ninja version 1.11.1
• pkg-config version 1.8.0

[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
• Linux (desktop) • linux  • linux-x64      • Manjaro Linux 6.0.0-1-MANJARO
• Chrome (web)    • chrome • web-javascript • Brave Browser 106.1.44.108

[✓] HTTP Host Availability
• All required HTTP hosts are available
</details>

**Comment by srawlins** [comment]
You might have filed your bug against the wrong repo. See the README for what this package does. It doesn't have any notions of "selection" or a "vertical axis."

**Comment by awh6al** [comment]
Sorry!!
