### ISSUE TITLE
Syntax nesting is not supported

### ISSUE THREAD

**Issue by fuyunmanbu** [dart-lang/markdown#483]
such as `~~**hello**~~`
Cannot be recognized at the same time

**Comment by srawlins** [comment]
Do you see this with various syntaxes, or just strikethrough (`~~`)?

**Comment by fuyunmanbu** [comment]
various syntaxes，The effect of syntax nesting together

**Comment by fuyunmanbu** [comment]
![Snip20221104_10](https://user-images.githubusercontent.com/16368126/199866573-35724c13-5cac-495d-8c79-018f3d64650f.png)
![Snip20221104_10](https://user-images.githubusercontent.com/16368126/199866582-1786173e-5359-4d61-abac-4f5a1e907505.png)

**Comment by fuyunmanbu** [comment]
![Snip20221104_9](https://user-images.githubusercontent.com/16368126/199866627-9d8d8691-6d01-4268-9478-0592f49a79cc.png)

**Comment by fuyunmanbu** [comment]
This effect works at the same time

**Comment by srawlins** [comment]
All of those examples have strikethrough. I imagine it only affects strikethrough.

**Comment by chenzhiguang** [comment]
I will fix that

**Comment by chenzhiguang** [comment]
@fuyunmanbu  I got what you mean. 🙂  The markdown package itself has no problem to parse the nesting strikethrough and strong emphasis, for example 
```dart
markdownToHtml('~~**hello**~~', extensionSet: ExtensionSet.gitHubFlavored)
```
will output:
```html
<p><del><strong>hello</strong></del></p>
```

You might need to report it [here](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+flutter_markdown%22) if you are using `flutter_markdown`.

**Comment by fuyunmanbu** [comment]
I found the problem after the test. I can support English, but not Chinese. Can you solve this problem?

**Comment by fuyunmanbu** [comment]
![Snip20221104_1](https://user-images.githubusercontent.com/16368126/199907807-b148a6f8-54db-417d-92bc-ca5ab3702fbf.png)
![Snip20221104_2](https://user-images.githubusercontent.com/16368126/199907846-eaa1f535-c47f-4319-967c-f22b16f9c2e2.png)

**Comment by fuyunmanbu** [comment]
![Snip20221104_4](https://user-images.githubusercontent.com/16368126/199908134-1b9a3d5e-2680-4adb-9953-dc35827c22f5.png)
![Snip20221104_5](https://user-images.githubusercontent.com/16368126/199908146-5098b488-d071-4d44-acfd-15ee7b06baee.png)

**Comment by fuyunmanbu** [comment]
I seem to have found the problem. There should be no content around

**Comment by fuyunmanbu** [comment]
![Snip20221104_6](https://user-images.githubusercontent.com/16368126/199908371-8c38b591-c1ef-463a-9aa0-32a87292d856.png)
It's not about language

**Comment by chenzhiguang** [comment]
@fuyunmanbu  Got it, thanks!

Then it is the expected behavior. Our `StrikethroughSyntax` follows the rules of [CommanMark delimiter run](https://spec.commonmark.org/0.30/#delimiter-run), it means if a  `~~` is followed by a  **Unicode punctuation character** it must be preceded by a **Unicode whitespace** or a **Unicode punctuation character**.

So these strikethroughs are valid:
```
Hello ~~**Markdown**~~!
Hello:~~**Markdown**~~!
```
But not this one:
```
Hello~~**Markdown**~~!
```

**Comment by fuyunmanbu** [comment]
Okay. Thank you very much.
