### ISSUE TITLE
publish 7.0.0?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/markdown#514]
I didn't see an existing issue for this; in terms of publishing a new major version - `7.0.0` - we may be good to go now. dartdoc has been updated to support the latest (pre-release) markdown, and both dartdoc and markdown have rolled into both the sdk and  google3.

**Comment by srawlins** [comment]
Super cool. I'll send a PR.

**Comment by devoncarew** [comment]
Published (thanks @srawlins)!
