### ISSUE TITLE
AutolinkExtensionSyntax regex does not work on Safari

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/markdown#515]
https://github.com/dart-lang/markdown/commit/49eefd21 added a regex in `AutolinkExtensionSyntax` that uses the `(?<=` and `(?<!` lookbehind operators.

These operators are not currently supported in the Safari browser.

See https://github.com/flutter/flutter/issues/120632

**Comment by kevmoo** [comment]
FYI @chenzhiguang – if you have thoughts

**Comment by kevmoo** [comment]
This is unfortunate, but it's unclear the overall priority of parsing markdown in Safari. Obviously a Flutter web scenario we care about.

**Comment by chenzhiguang** [comment]
I will fix it later today
