### ISSUE TITLE
Markdown converts [] space () to links

### ISSUE THREAD

**Issue by keertip** [dart-lang/markdown#53]
Take a look at 

https://github.com/dart-lang/sdk/blob/master/sdk/lib/developer/developer.dart#L40

Markdown converts it to links

https://api.dartlang.org/1.12.1/dart-developer/log.html

**Comment by srawlins** [comment]
A few implementations do convert that text into links ([Babelmark](http://johnmacfarlane.net/babelmark2/?text=A+%5Blink%5D+(with)+a+space.)), but most do not, including: Pandoc, Markdown.pl, commonmark, and markdown GFM. I think this is a legitimate bug.

**Comment by munificent** [comment]
+1, I think that's a bug.
