### ISSUE TITLE
Support line/column offset in original text

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/markdown#534]
It would be great if `Node` had a `Node.span` property that was an instance of `SourceSpan` from [`package:source_span`](https://pub.dev/packages/source_span).

It would make it easier to provide accurate error messages, if there is something in the parsed output we wish to disallow later.

**Comment by srawlins** [comment]
Do you mean a `SourceSpan` that would point to the outputted text?

**Comment by jonasfj** [comment]
I mean that when we've parsed a markdown string. It'd be nice if the [`Element`](https://pub.dev/documentation/markdown/latest/markdown/Element-class.html) and [`Text`](https://pub.dev/documentation/markdown/latest/markdown/Text-class.html), which both implement [`Node`](https://pub.dev/documentation/markdown/latest/markdown/Node-class.html), had a `span` property with the type [`SourceSpan`](https://pub.dev/documentation/source_span/latest/source_span/SourceSpan-class.html).

Where the `span` property points to substring in the input markdown that gave rise to the markup.

-------------

**Example**

    # Hello World!
    
    ```dart
    void main() => print('hello');
    ```

Would be parsed to:
 * `Element` with
   * `tag = 'h1'`
   * `span = SourceSpan(SourceLocation(0), SourceLocation(14), '# Hello World!')`
   * `children` as
      * `Text` with
        * `span = SourceSpan(SourceLocation(2), SourceLocation(14), 'Hello World!')`
        * `textContent = "Hello World!"`
 * `Element` with
   * `tag = 'pre'`
   * `span = SourceSpan(SourceLocation(16), SourceLocation(58), '```dart\nvoid main() => print('hello');\n```')`
   * `children` as
      * `Element` with
        * `tag = 'code'`
        * `attributes = {'class': 'language-dart'}`
        * `span = SourceSpan(SourceLocation(16), SourceLocation(58), '```dart\nvoid main() => print('hello');\n```')`
        * `children` as
          * `Text` with
          * `span = SourceSpan(SourceLocation(24), SourceLocation(54), 'void main() => print('hello');')`
          * `textContent = "Hello World!"`

(I'm sure I counted something wrong in my example :rofl: )

**Comment by jonasfj** [comment]
Closing as a duplicate of https://github.com/dart-lang/markdown/issues/369

**Comment by chenzhiguang** [comment]
@jonasfj  Hello Jonas, I have implemented the `SourceSpan` in this repository: https://github.com/tagnote-app/dart_markdown#syntax-tree. The purpose of this addition was to add `SourceSpan` support, but there were too many changes which made the PR difficult to review, so I created a separate repository. Perhaps we can consider migrating these features to our main package
