### ISSUE TITLE
Render the "alert" markdown extension

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/markdown#567]
```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

See https://github.com/orgs/community/discussions/16925

**Comment by shikharish** [comment]
Hello, I would like to work on this issue.

**Comment by srawlins** [comment]
We would probably accept a PR implementing this, even though it is not specified in https://github.github.com/gfm/ 😠 😡 😠 

You can use Markdown text boxes, like this comment box, as a testbed for what GitHub renders. I think we just want to render the right `div` and `p` elements, with specific CSS classes. The end clients will then be responsible for making those CSS classes available.

And rigorous testing 😄

**Comment by shikharish** [comment]
Thank you for the response!
I am new here; excited to contribute to the dart ecosystem!
I could not find a contributing guide to this repo(have never contributed to a dart package before). If you could help me with setting up a development environment that would be really helpful.
