### ISSUE TITLE
Github single tilde strikethrough

### ISSUE THREAD

**Issue by robertoestivill** [dart-lang/markdown#592]
I'm using this library through [flutter_markdown](https://pub.dev/packages/flutter_markdown) and I'm having issues supporting single tilde `~` strikethrough. 

From the [Github Flavored Markdown specification](
https://github.github.com/gfm/#strikethrough-extension-) I can see that single tilde should also produce strike through text.

<img width="871" alt="Screenshot 2024-03-05 at 10 23 09" src="https://github.com/dart-lang/markdown/assets/3728545/30a8c056-afa1-4c54-8db4-5469861b9f72">

<details>
<summary>My reproducible example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:markdown/markdown.dart' as md;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    const markdown = '~~this works~~ \n\n~this doesnt work~';

    print(
      md.markdownToHtml(
        markdown,
        extensionSet: md.ExtensionSet.gitHubFlavored,
      ),
    );

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text(
            'Markdown bug report\nSingle tildes not working',
          ),
        ),
        body: Markdown(
          data: markdown,
          extensionSet: md.ExtensionSet.gitHubFlavored,
        ),
      ),
    );
  }
}
```

</details>

Generates the following outputs

<img width="544" alt="Screenshot 2024-03-05 at 10 55 37" src="https://github.com/dart-lang/markdown/assets/3728545/a1d36a64-9a11-4b9e-8511-efc29c3b97ae">

<br/>
<img width="251" alt="Screenshot 2024-03-05 at 10 58 22" src="https://github.com/dart-lang/markdown/assets/3728545/6a4381ef-bb40-4cd0-bdbe-c276f8237eec">

As you can see in the last console screenshot, the lack of `<del>` elements in the second line is the problem and the reason why I decided to create the bug in this repository instead of creating it in `flutter_markdown`. 

<details>
 <summary> flutter doctor</summary>

```
➜  bugreport fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```
</details>

Any ideas? What am I missing?
Cheers

**Comment by srawlins** [comment]
I think it's a bug. Reproduces at https://dart-lang.github.io/markdown/

And it appears we have only have unit tests for `~~`. But the pattern that we use for StrikethroughSyntax is `'~+'` which should support single tildes. Not sure what's going on.
