### ISSUE TITLE
When Image src encoded, it changes the valid url to mismatched one

### ISSUE THREAD

**Issue by mym0404** [dart-lang/markdown#597]
The image url is encoded since #589

Valid Image Url

https://firebasestorage.googleapis.com/v0/b/jagyeok-001.appspot.com/o/exam001%2Fexam001_687_2a0829c9-0349-425e-8615-a309d9d6fbca%7D.png?alt=media&token=17242a6e-ba12-47a6-a567-2f7b88c34229

Transformed Image Url

https://firebasestorage.googleapis.com/v0/b/jagyeok-001.appspot.com/o/exam001/exam001_687_2a0829c9-0349-425e-8615-a309d9d6fbca%7D.png?alt=media&token=17242a6e-ba12-47a6-a567-2f7b88c34229

`%2F` is converted to `/`. It is a misbehavior.

This should be correctly shown in [commonmark spec](https://spec.commonmark.org/dingus/).

![image](https://github.com/dart-lang/markdown/assets/33388801/f8b1b87b-0f14-4d99-924d-d940019fc21c)

**Comment by srawlins** [comment]
Oh ouch! Good catch

**Comment by manafire** [comment]
Oh boy.  Well, this certainly explains why most of my Cloud Storage images are broken in my app!  

I'm getting this behaviour in v7.2.2 from [flutter_markdown](https://pub.dev/packages/flutter_markdown/) which [depends on markdown: ^7.1.1](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/pubspec.yaml).  Any chance of this making it into a 7.2.3 release soon??

**Comment by zhouzhuo810** [comment]
valid url:
```
[https://ohpm.openharmony.cn/#/cn/detail/@ohos%2Faxios](https://ohpm.openharmony.cn/#/cn/detail/@ohos%2Faxios)
```
Transformed url : https://ohpm.openharmony.cn/#/cn/detail/@ohos/axios 

`%2F` is also converted to  `/`
