### ISSUE TITLE
Add support for Custom Heading Ids - header_atributes

### ISSUE THREAD

**Issue by GiancarloCante** [dart-lang/markdown#620]
Hello

It would be nice to be able to define a custom id for the headers.

https://pandoc.org/MANUAL.html#extension-header_attributes
https://www.markdownguide.org/extended-syntax/#heading-ids

Example
```md
# My heading {#foo-id}
```
```html
<h1 id="foo-id">My heading</h1>
```

**Comment by srawlins** [comment]
This package only aims to support CommonMark and GitHub-Flavored Markdown.

However, the package is designed, a little bit, with extensibility in mind. For example, see how we support GitHub-Flavored Markdown's header IDs [here](https://github.com/dart-lang/markdown/blob/master/lib/src/extension_set.dart#L58). With this example in mind, I think it should be possible, and straightforward, to write a "pandoc header attributes" syntax.

I do love pandoc, and all of its extensions over CommonMark, but we don't have the bandwidth to extend the purview of this package to cover the pandoc extensions (including shipping high quality releases, tackling bugs, and working towards supporting _all_ of the pandoc syntax). I think that a community-supported "Pandoc markdown" package which is based on this package, with additional syntaxes, would be a great solution.
