### ISSUE TITLE
Provide a way for using package:markdown with custom syntax highlighter for inline/block code quotes

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/markdown#67]
It would be very nice if one could use `package:markdown` and provide custom syntax highlighter plugins for inline and block code quotes. The [pub-dartlang-dart](https://github.com/dart-lang/pub-dartlang-dart) server app contains a simplified [syntax highlighter for Dart](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/colored_markdown.dart) -- though only with patches to the markdown package.

One way of doing this would be to:
a) let the **renderer** take care of html rendering and remove the escaping from the parser
b) allow passing custom formatters to the `HtmlRenderer`

For a) one can see that html escaping happens already when parsing:
```dart
class CodeBlockSyntax {
  ...
  Node parse(BlockParser parser) {
    ...
    var escaped = escapeHtml(childLines.join('\n'));
    return new Element('pre', [new Element.text('code', escaped)]);
  }
}
```

**Comment by kevmoo** [comment]
@srawlins Thoughts on this?

**Comment by srawlins** [comment]
I support the idea. Very nice for server-side formatting.

a) is not really attractive to me. Right now the parser creates Elements, which describe their tag, attributes, and text, already processed for HTML characters. I don't like the idea of special-casing "code" elements, and HTML-escaping them in the renderer. (And HTML-escaping everything in the renderer would surely have a performance hit.)

b) is OK. I can envision a pretty simple API for that:

```dart
abstract class HtmlFormatter {
  /// modify will be called before each node (Elements and Texts)  is rendered to HTML.
  void modify(Node node);
}
```

c) However, I think its just as easy to format the nodes by visiting them yourself:

```dart
CodeSyntaxHilighter extends NodeVisitor {
  bool visitElementBefore(Element element) {
  if (element.tag == "pre" || element.tag == "code") {
    // Unescape HTML in text, and hilight it into a tree of <span>s and whatnot.
  }
}
```

Then you amend the rendering pipeline:

```dart
String markdownToHilightedHtml(...) {
  var document = new Document(...);

  var lines = markdown.replaceAll('\r\n', '\n').split('\n');
  document.parseRefLinks(lines);

  List<Node> ast = document.parseLines(lines);
  new CodeSyntaxHilighter.hilight(ast);
  return renderToHtml(ast) + '\n';
}
```

This requires no change to the markdown package, and is the same level of complexity for the formatting tool.

This does require _un_ escaping the HTML, but I think this is the lesser of two evil processes, as it's trivial to reverse [`escapeHtml`](https://github.com/dart-lang/markdown/blob/master/lib/src/util.dart).

At this point I'm going to suggest c). What do you think?

**Comment by munificent** [comment]
+1 for doing a visitor over the AST. That kind of stuff is why the package separates out parsing and rendering.

**Comment by mkustermann** [comment]
I've taken the visitor approach now, since it allows us to use `package:markdown` as it is published. There are two things which were unfortunate:
  * We don't have a simple way of **un**escaping HTML (the opposite of `dart:convert`s `HtmlEscape` class is missing)
  * If I generate from source code a number of `<span>` elements inside a `<pre>`, then the default renderer will insert newlines (the check which uses `_blockTags = new RegExp('blockquote|h1|h2|h3|h4|h5|h6|hr|p|pre')` is flat, it should also work if a node is arbitrarily nested under one of these tags, no additional lines should be added in that case)

Both of these issues can be worked around, though :)

My original comment was more ment to have an actual AST, which represents the syntax/semantics of markdown (i.e. no html element generation, no html escaping). Then one would be able to have different renderer backends: e.g. html/text/manpage. (Currently the parser will already render the markdown, it's just a tree instead of the final html string).

Feel free to close this issue if you'd like.

**Comment by mkustermann** [comment]
I'll close this issue, since the visitor method works for making a custom syntax highlighter and making the parser produce an intermediate form (instead of html) would be a major change to the package.
