### ISSUE TITLE
Large Files?

### ISSUE THREAD

**Issue by alexisargyris** [dart-lang/markdown#7]
Is there some kind of size limitation that we should be aware of?
Small files (less than 50kb) get converted with no problem, but larger (more than 500kb) ones fail silently (somewhere inside the loop that converts markdown lines to AST nodes).
Any suggestions on what might be the problem / how to debug this?

**Comment by jkleiser** [comment]
I had no problem converting a 164KB .md file, and it took less than a second on my not so modern iMac. The only thing I'm missing is tables.

**Comment by srawlins** [comment]
There should not be any limitation on size, and recently an exponential-time parsing bug was fixed. Imma close this for now. Please re-open with links to specific MD files or scripts that generate MD files that take unexpected time to parse.
