### ISSUE TITLE
use markdown in client side error

### ISSUE THREAD

**Issue by meflyup** [dart-lang/markdown#82]
when I use markdown in index.html and index.dart,it shows error:
`Internal error: 'package:markdown/src/document.dart': error: line 23 pos 39: unexpected token '?'
    this.extensionSet = extensionSet ?? ExtensionSet.commonMark;
`
```
library my_project.web.index;

import 'package:mypaper/main_app.dart';
import 'package:polymer/polymer.dart';
import 'dart:html';
import 'package:markdown/markdown.dart';
import 'package:codemirror/codemirror.dart';
/// [MainApp] used!
main() async {
  await initPolymer();
  Map options = {
    'mode': 'html',
    'theme': 'monokai'
  };

  CodeMirror editor = new CodeMirror.fromElement(
      querySelector('#textContainer'), options: options);
  editor.getDoc().setValue(markdownToHtml("## bhtml"));
/*  String markdown2Html=markdownToHtml(markdown);*/

  CodeMirror editor1 = new CodeMirror.fromElement(
      querySelector('#textContainer2'), options: options);
  editor1.getDoc().setValue("# html");
}
updateViewer(){

}```

**Comment by srawlins** [comment]
Looks like your Dart doesn't have null-aware operators, [introduced](http://news.dartlang.org/2015/08/dart-112-released-with-null-aware.html) in 1.12.0. What vertsion of Dart do you have?

**Comment by meflyup** [comment]
I have dart-sdk-1.14.0,
thanks.

**Comment by srawlins** [comment]
Hi @meflyup, sorry for the delay. I can't reproduce this. What browser are you using? Where do you see the error?

If you're compiling to JavaScript, can you post `dart2js --version`; if you're serving with pub, can you post `pub --version`? Thanks

**Comment by meflyup** [comment]
Thanks !   @srawlins  It's realted to the version of dart sdk. it work now. Sorry, I Have stopped the previous work for a long time.
